const $=id=>document.getElementById(id);
const fmtMoney=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const fmt=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Math.round(n));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

const START={month:1,cash:1000,users:80,customers:4,price:12,team:1,employees:0,salaryPerEmployee:1100,marketing:0,infraLevel:1,reputation:50,product:42,growth:.10,conversion:.05,equity:1,debt:0,totalRaised:0,valuation:5000,revenue:48,expenses:0,profit:0,history:[],flags:{},lastEventMonth:{}};
let state={},currentEvent=null;

const events=[
{id:'first-client',category:'CLIENT',risk:'Décision commerciale',cooldown:99,condition:s=>s.month<=5&&!s.flags.firstClient,title:'Un prospect te propose 900 € pour une demande sur mesure',description:'Le cash peut te donner de l’air, mais tu risques de détourner le produit de ta vision.',choices:[{label:'Accepter le contrat',hint:'+900 € maintenant · Produit -3 · Réputation +3',cost:0,apply:s=>{s.cash+=900;s.product-=3;s.reputation+=3;s.flags.firstClient=true}},{label:'Refuser et garder le cap',hint:'0 € maintenant · Produit +6 · Réputation +1',cost:0,apply:s=>{s.product+=6;s.reputation+=1;s.flags.firstClient=true}}]},
{id:'marketing',category:'CROISSANCE',risk:'Coût mensuel',cooldown:4,condition:s=>s.month>=2,title:'Quel budget acquisition veux-tu fixer ?',description:'Ce budget sera payé chaque mois. Plus tu dépenses, plus tu accélères, mais ton runway diminue.',choices:[{label:'Rester en organique',hint:'Marketing : 0 €/mois',cost:0,apply:s=>s.marketing=0},{label:'Tester doucement',hint:'Marketing : 300 €/mois',cost:0,apply:s=>s.marketing=300},{label:'Accélérer fort',hint:'Marketing : 900 €/mois',cost:0,apply:s=>s.marketing=900}]},
{id:'pricing',category:'PRICING',risk:'Impact conversion',cooldown:5,condition:s=>s.customers>=8,title:'Tes clients paient. Quel prix veux-tu tester ?',description:'Un prix plus élevé augmente le revenu par client mais réduit la conversion.',choices:[{label:'9 € / mois',hint:'Conversion +1,5 pt · revenu/client plus faible',cost:0,apply:s=>{s.price=9;s.conversion+=.015}},{label:'19 € / mois',hint:'Positionnement équilibré',cost:0,apply:s=>{s.price=19;s.conversion-=.002}},{label:'39 € / mois',hint:'Conversion -1,5 pt · Réputation +2',cost:0,apply:s=>{s.price=39;s.conversion-=.015;s.reputation+=2}}]},
{id:'hire',category:'ÉQUIPE',risk:'Coût fixe',cooldown:5,condition:s=>s.month>=3&&s.employees<8,title:'Tu commences à manquer de temps. Recrutes-tu ?',description:'Tu ne te verses pas de salaire. Seuls les employés recrutés ajoutent un coût salarial mensuel.',choices:[{label:'Rester seul',hint:'0 € maintenant · 0 €/mois de salaire · Produit +2',cost:0,apply:s=>s.product+=2},{label:'Recruter 1 personne',hint:'-700 € maintenant · +1 100 €/mois · Produit +8',cost:700,apply:s=>{s.cash-=700;s.employees++;s.team++;s.product+=8}},{label:'Recruter 2 personnes',hint:'-1 200 € maintenant · +2 200 €/mois · Produit +14',cost:1200,apply:s=>{s.cash-=1200;s.employees+=2;s.team+=2;s.product+=14}}]},
{id:'seed',category:'INVESTISSEUR',risk:'Dilution',cooldown:99,condition:s=>s.month>=4&&!s.flags.seed&&s.valuation>=12000,title:'Un investisseur propose 25 000 € contre 20 %',description:'Tu gagnes beaucoup de runway, mais ta part passe de 100 % à 80 %.',choices:[{label:'Accepter',hint:'+25 000 € · ta part × 80 %',cost:0,apply:s=>{s.cash+=25000;s.equity*=.8;s.totalRaised+=25000;s.flags.seed=true;s.reputation+=4}},{label:'Refuser',hint:'Pas de cash · aucune dilution',cost:0,apply:s=>{s.flags.seed=true;s.reputation+=1}}]},
{id:'infra',category:'INFRA',risk:'Capacité',cooldown:4,condition:s=>s.users>1800*s.infraLevel,title:'Tes serveurs approchent de leur limite',description:'Tu peux investir maintenant ou risquer une panne qui fera partir des utilisateurs.',choices:[{label:'Augmenter la capacité',hint:'-1 500 € maintenant · +120 €/mois',cost:1500,apply:s=>{s.cash-=1500;s.infraLevel++;s.reputation+=2}},{label:'Attendre',hint:'0 € maintenant · 55 % de risque de panne',cost:0,apply:s=>{if(Math.random()<.55){s.reputation-=14;s.users*=.86;s.product-=4}else s.reputation-=2}}]},
{id:'viral',category:'CROISSANCE',risk:'Opportunité',cooldown:8,condition:s=>s.product>=55&&s.reputation>=50,title:'Une vidéo sur ton produit devient virale',description:'Tu peux profiter du trafic gratuitement ou acheter davantage de portée.',choices:[{label:'Laisser l’organique travailler',hint:'0 € · Utilisateurs +22 %',cost:0,apply:s=>{s.users*=1.22;s.reputation+=3}},{label:'Amplifier la campagne',hint:'-2 000 € · Utilisateurs +55 %',cost:2000,apply:s=>{s.cash-=2000;s.users*=1.55;s.reputation+=5}}]},
{id:'enterprise',category:'VENTE',risk:'Cash immédiat',cooldown:8,condition:s=>s.product>=68&&s.team>=2,title:'Une PME veut prépayer un contrat annuel',description:'Elle apporte 12 000 € de cash, mais demande une adaptation du produit.',choices:[{label:'Signer',hint:'+12 000 € · Produit -4 · Réputation +8',cost:0,apply:s=>{s.cash+=12000;s.product-=4;s.reputation+=8}},{label:'Refuser',hint:'0 € · Produit +6 · Croissance +2 pts',cost:0,apply:s=>{s.product+=6;s.growth+=.02}}]},
{id:'competitor',category:'CONCURRENCE',risk:'Pression marché',cooldown:8,condition:s=>s.users>=2500,title:'Un concurrent copie ta fonctionnalité principale',description:'Tu dois choisir entre différenciation, prix ou conservation du cash.',choices:[{label:'Accélérer le produit',hint:'-2 500 € · Produit +14 · Réputation +4',cost:2500,apply:s=>{s.cash-=2500;s.product+=14;s.reputation+=4}},{label:'Baisser le prix',hint:'Prix -25 % · Conversion +1,2 pt',cost:0,apply:s=>{s.price=Math.max(5,s.price*.75);s.conversion+=.012}},{label:'Ne rien faire',hint:'0 € · Croissance -3 pts · Réputation -3',cost:0,apply:s=>{s.growth-=.03;s.reputation-=3}}]}
];

function expenseBreakdown(){const salaries=state.employees*state.salaryPerEmployee,infra=Math.round(120+state.infraLevel*80+state.users*.02),marketing=state.marketing,debtCost=Math.round(state.debt*.02);return{salaries,infra,marketing,debtCost,total:salaries+infra+marketing+debtCost}}
function recalcEconomy(){state.product=clamp(state.product,5,100);state.reputation=clamp(state.reputation,0,100);state.conversion=clamp(state.conversion,.01,.22);state.growth=clamp(state.growth,.01,.55);const pf=.55+state.product/100,rf=.65+state.reputation/140,tf=1+Math.log2(Math.max(1,state.team))*.08,marketingUsers=state.marketing*(.65+state.reputation/100),organic=state.users*state.growth*pf*rf*tf,churn=state.users*clamp(.09-state.product*.00055-state.reputation*.00025,.012,.10);state.users=Math.max(30,Math.round(state.users+organic+marketingUsers-churn));const pricePenalty=Math.max(.45,1-(state.price-12)*.012),effective=clamp(state.conversion*pricePenalty*(.7+state.product/125),.01,.25);state.customers=Math.max(1,Math.round(state.users*effective));state.revenue=Math.round(state.customers*state.price);const b=expenseBreakdown();state.expenses=Math.round(b.total);state.profit=state.revenue-state.expenses;state.cash+=state.profit;const annual=state.revenue*12,gp=2.2+state.growth*8,qp=(.65+state.product/180)*(.7+state.reputation/200),pb=state.profit>0?1.2:.85;state.valuation=Math.max(1000,Math.round(annual*gp*qp*pb+Math.max(0,state.cash)*.6-state.debt*.35))}
function recalcSnapshotOnly(){state.revenue=Math.round(state.customers*state.price);state.expenses=Math.round(expenseBreakdown().total);state.profit=state.revenue-state.expenses;const annual=state.revenue*12;state.valuation=Math.max(1000,Math.round(annual*(2.2+state.growth*8)*(.65+state.product/180)*(.7+state.reputation/200)*.85+state.cash*.6-state.debt*.35))}
function getAvailableEvents(){return events.filter(e=>e.condition(state)&&(state.month-(state.lastEventMonth[e.id]||-99)>=e.cooldown))}
function pickEvent(){const a=getAvailableEvents();if(!a.length)return makeRoutineEvent();const e=a[Math.floor(Math.random()*a.length)];state.lastEventMonth[e.id]=state.month;return e}
function makeRoutineEvent(){return{id:'routine-'+state.month,category:'STRATÉGIE',risk:'Décision mensuelle',title:'Sur quoi veux-tu concentrer ce mois ?',description:'Aucune urgence majeure. Choisis selon ta trésorerie et ton objectif.',choices:[{label:'Améliorer le produit',hint:'-250 € · Produit +6',cost:250,apply:s=>{s.cash-=250;s.product+=6}},{label:'Chercher des utilisateurs',hint:'-350 € · Utilisateurs +12 % · Réputation -1',cost:350,apply:s=>{s.cash-=350;s.users*=1.12;s.reputation-=1}},{label:'Préserver le cash',hint:'0 € · Conversion +0,3 pt',cost:0,apply:s=>{s.conversion+=.003}}]}}
function resetGame(){state=JSON.parse(JSON.stringify(START));recalcSnapshotOnly();pushHistory();$('start-screen').classList.add('hidden');$('end-screen').classList.add('hidden');$('game-screen').classList.remove('hidden');$('feed').innerHTML='';addFeed('Mois 1',`Départ : ${fmtMoney(state.cash)} de cash, aucun salarié, ${fmtMoney(state.expenses)}/mois de coûts techniques.`);render();showEvent()}
function financingEvent(){const need=Math.max(1000,Math.ceil(Math.abs(state.cash)+state.expenses*2));const bridge=Math.min(Math.max(2500,need),Math.max(2500,state.valuation*.35));return{id:'rescue-'+state.month,category:'FINANCEMENT',risk:'Trésorerie critique',title:'Ta trésorerie est négative, mais la startup a encore de la valeur',description:`Tu as ${fmtMoney(state.cash)} de cash pour une valorisation de ${fmtMoney(state.valuation)}. Tu n’es pas automatiquement mort : il faut trouver du financement.`,choices:[{label:'Bridge investisseur',hint:`+${fmtMoney(bridge)} · dilution de 12 %`,cost:0,apply:s=>{s.cash+=bridge;s.equity*=.88;s.totalRaised+=bridge;s.reputation-=1}},{label:'Dette court terme',hint:`+${fmtMoney(bridge)} · dette +${fmtMoney(bridge)} · coût financier mensuel`,cost:0,apply:s=>{s.cash+=bridge;s.debt+=bridge;s.reputation-=2}},{label:'Arrêter la société',hint:'Mettre fin à la run maintenant',cost:0,quit:true,apply:s=>{}}]}}
function choose(choice){if(choice.cost&&choice.cost>state.cash)return;if(choice.quit)return endGame(false,'cash');choice.apply(state);state.month++;recalcEconomy();pushHistory();addFeed('Mois '+state.month,choice.label+' — '+monthlySummary());render();if(state.reputation<=0)return endGame(false,'reputation');if(state.month>96)return endGame(false,'time');if(state.valuation>=1e9)return endGame(true,'win');if(state.cash<0){if(state.valuation>=Math.max(2500,Math.abs(state.cash)*2)&&state.reputation>=20){currentEvent=financingEvent();return renderCurrentEvent()}return endGame(false,'cash')}setTimeout(showEvent,130)}
function monthlySummary(){const b=expenseBreakdown(),p=state.profit>=0?`+${fmtMoney(state.profit)}`:fmtMoney(state.profit);return `${fmt(state.customers)} clients · CA ${fmtMoney(state.revenue)} · coûts ${fmtMoney(state.expenses)} (salaires ${fmtMoney(b.salaries)}, infra ${fmtMoney(b.infra)}, marketing ${fmtMoney(b.marketing)}, dette ${fmtMoney(b.debtCost)}) · résultat ${p}.`}
function renderCurrentEvent(){const e=currentEvent;$('event-title').textContent=e.title;$('event-description').textContent=e.description;$('event-category').textContent=e.category;$('event-risk').textContent=e.risk;$('choices').innerHTML='';e.choices.forEach(c=>{const btn=document.createElement('button');btn.className='choice-btn';const blocked=c.cost&&c.cost>state.cash;btn.disabled=blocked;if(blocked)btn.style.opacity='.45';btn.innerHTML=`<strong>${c.label}</strong><span>${c.hint}${blocked?' · Cash insuffisant':''}</span>`;btn.addEventListener('click',()=>choose(c));$('choices').appendChild(btn)})}
function showEvent(){currentEvent=pickEvent();renderCurrentEvent()}
function pushHistory(){state.history.push({month:state.month,cash:Math.round(state.cash),valuation:Math.round(state.valuation),revenue:Math.round(state.revenue)})}
function render(){const b=expenseBreakdown();$('cash').textContent=fmtMoney(state.cash);$('revenue').textContent=fmtMoney(state.revenue);$('expenses').textContent=fmtMoney(state.expenses);$('expenses').title=`Salaires ${fmtMoney(b.salaries)} · Infra ${fmtMoney(b.infra)} · Marketing ${fmtMoney(b.marketing)} · Dette ${fmtMoney(b.debtCost)}`;$('valuation').textContent=fmtMoney(state.valuation);$('users').textContent=fmt(state.users);$('customers').textContent=fmt(state.customers);$('team').textContent=state.employees===0?'Solo':`${fmt(state.team)} (${fmt(state.employees)} salarié${state.employees>1?'s':''})`;$('equity').textContent=(state.equity*100).toFixed(1)+' %';$('price').textContent=fmtMoney(state.price)+'/mois';$('conversion').textContent=(state.customers/state.users*100).toFixed(1)+' %';$('reputation').textContent=Math.round(state.reputation)+'/100';$('product').textContent=Math.round(state.product)+'/100';$('growth').textContent=(state.growth*100).toFixed(1)+' %';$('month-label').textContent='Mois '+state.month;$('cash').className=state.cash<0?'negative':'';$('revenue').className=state.profit>=0?'positive':'';drawChart()}
function drawChart(){const canvas=$('history-chart'),dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(),width=Math.max(300,rect.width||900),height=260;canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);const pad={l:52,r:16,t:18,b:30},w=width-pad.l-pad.r,h=height-pad.t-pad.b,hist=state.history;if(!hist.length)return;const max=Math.max(1000,...hist.flatMap(p=>[Math.max(0,p.valuation),Math.max(0,p.cash)]))*1.08;ctx.strokeStyle='rgba(143,155,170,.18)';ctx.fillStyle='#8f9baa';ctx.font='11px system-ui';for(let i=0;i<=4;i++){const y=pad.t+h*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke();ctx.fillText(compactMoney(max*(1-i/4)),4,y+4)}const plot=(k,c)=>{ctx.strokeStyle=c;ctx.lineWidth=2.5;ctx.beginPath();hist.forEach((p,i)=>{const x=pad.l+(hist.length===1?w/2:i*w/Math.max(1,hist.length-1)),y=pad.t+h-(Math.max(0,p[k])/max)*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};plot('valuation','#77f29c');plot('cash','#79a8ff');ctx.fillStyle='#8f9baa';ctx.fillText('M1',pad.l,height-8);ctx.textAlign='right';ctx.fillText('M'+state.month,width-pad.r,height-8);ctx.textAlign='left'}
function compactMoney(n){if(n>=1e9)return(n/1e9).toFixed(1)+' Md€';if(n>=1e6)return(n/1e6).toFixed(1)+' M€';if(n>=1e3)return(n/1e3).toFixed(0)+' k€';return Math.round(n)+' €'}
function addFeed(label,text){const item=document.createElement('div');item.className='feed-item';item.innerHTML=`<b>${label}</b><span>${text}</span>`;$('feed').prepend(item)}
function endGame(won,reason){$('game-screen').classList.add('hidden');$('end-screen').classList.remove('hidden');const worth=state.valuation*state.equity,b=expenseBreakdown();$('end-kicker').textContent=won?'UNICORNE':'FIN DE RUN';$('end-title').textContent=won?'Ta startup vaut 1 milliard.':'La startup n’a pas survécu.';const reasons={cash:`Tu n’as plus réussi à financer l’entreprise. Dernier mois : ${fmtMoney(state.revenue)} de revenus pour ${fmtMoney(state.expenses)} de dépenses.`,reputation:'Ta réputation est tombée à zéro.',time:'Après 8 ans, tu n’as pas atteint le milliard.'};$('end-copy').textContent=won?`Tu possèdes encore ${(state.equity*100).toFixed(1)} %. Valeur théorique de ta part : ${fmtMoney(worth)}.`:reasons[reason];$('end-valuation').textContent=fmtMoney(state.valuation);$('end-equity').textContent=(state.equity*100).toFixed(1)+' %';$('end-worth').textContent=fmtMoney(worth);$('end-revenue').textContent=fmtMoney(state.revenue)}
$('start-btn').addEventListener('click',resetGame);$('restart-btn').addEventListener('click',resetGame);$('play-again-btn').addEventListener('click',resetGame);window.addEventListener('resize',()=>{if(state.history?.length)drawChart()});