const $ = id => document.getElementById(id);
const fmtMoney = n => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Math.round(n || 0));
const fmt = n => new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Math.round(n || 0));
const clamp = (n,a,b) => Math.max(a,Math.min(b,n));

const START = {month:1,cash:1000,users:80,customers:4,price:12,team:1,employees:0,salaryPerEmployee:1100,marketing:0,infraLevel:1,infraEfficiency:1,reputation:50,product:42,growth:.10,conversion:.05,compliance:50,equity:1,debt:0,totalRaised:0,valuation:5000,revenue:48,expenses:0,profit:0,history:[],flags:{seen:{},seenCount:0},lastCategory:''};
let state={},currentEvent=null,pendingEnd=null,awaitingContinue=false;

const SCENARIO_BANK={
PRODUCT:[
["40 % des nouveaux inscrits quittent l’onboarding","Ton produit attire du monde, mais beaucoup abandonnent avant de comprendre sa valeur."],
["Un gros client réclame une fonctionnalité qui n’était pas prévue","La demande peut débloquer un contrat, mais elle détourne la roadmap."],
["Tes utilisateurs demandent une vraie expérience mobile","Le web fonctionne, mais l’usage sur téléphone commence à devenir un frein."],
["La dernière mise à jour a introduit plusieurs bugs visibles","La croissance continue, mais les tickets support montent rapidement."],
["Une fonctionnalité IA devient incontournable dans ton secteur","Le marché en parle beaucoup, mais la construire vite peut dégrader le cœur du produit."],
["Trois intégrations sont demandées en même temps","Chaque intégration peut ouvrir un segment différent, mais l’équipe ne peut pas tout faire."],
["Les utilisateurs gratuits consomment beaucoup sans convertir","Ton offre gratuite aide la croissance mais commence à coûter cher."],
["La dette technique ralentit chaque nouvelle fonctionnalité","Continuer à empiler du code est rapide aujourd’hui, mais de plus en plus risqué."],
["Un client signale que le produit est difficile à utiliser avec un lecteur d’écran","Le problème touche peu d’utilisateurs aujourd’hui, mais révèle une faiblesse d’accessibilité."],
["La roadmap est devenue trop large","Tu as dix bonnes idées et des ressources pour en exécuter trois correctement."]],
SALES:[
["Un prospect veut tester le produit pendant 30 jours avant de payer","Le logo serait intéressant, mais le pilote mobilisera du temps."],
["Un client propose de payer un an d’avance contre une grosse remise","Le cash immédiat est précieux, mais la remise réduit la valeur du contrat."],
["Une entreprise demande un questionnaire sécurité de 80 pages","Le contrat est sérieux, mais le cycle de vente devient beaucoup plus lourd."],
["Une agence veut revendre ton produit à ses propres clients","Le canal peut accélérer les ventes, mais tu perdras une partie de la marge."],
["Un ancien client veut revenir si tu corriges deux irritants précis","Le besoin est clair et mesurable, mais il faut décider s’il représente vraiment le marché."],
["Un prospect étranger veut signer rapidement","L’opportunité est réelle, mais le support et la facturation seront plus complexes."],
["Un grand compte bloque la signature au service achats","Le produit est validé, mais le paiement peut encore prendre plusieurs mois."],
["Tes meilleurs clients demandent un accompagnement premium","Le service peut augmenter le revenu, mais il rend le modèle moins automatique."],
["Une startup connue demande un pilote gratuit contre son logo","Le logo peut rassurer d’autres prospects, mais la visibilité ne paie pas les factures."],
["Un seul client représente bientôt une grosse part de ton revenu","Le contrat sécurise le cash mais crée une dépendance dangereuse."]],
MARKETING:[
["Un créateur de contenu parle spontanément de ton produit","Tu peux amplifier la vague ou laisser l’effet organique suivre son cours."],
["Tes publicités coûtent de plus en plus cher","Le trafic arrive toujours, mais le coût d’acquisition se rapproche de la valeur des clients."],
["Un article de blog commence à bien se positionner sur Google","Tu peux investir dans le SEO ou garder l’équipe concentrée sur le produit."],
["Une newsletter de niche te propose un sponsoring","L’audience est petite mais très proche de ta cible."],
["Tes clients demandent un programme de parrainage","Le bouche-à-oreille existe déjà, mais il faut décider combien tu es prêt à offrir."],
["Une plateforme de lancement te propose une mise en avant","Le pic de trafic peut être fort mais très court."],
["Un salon professionnel approche","Un stand coûte cher, mais plusieurs grands comptes de ta cible seront présents."],
["Ton message marketing ne correspond plus vraiment au produit","Les chiffres sont corrects, mais les prospects comprennent mal ce qui te différencie."],
["Une communauté d’utilisateurs commence à se former sans toi","Tu peux la structurer ou la laisser rester totalement organique."],
["Une campagne devient virale pour une raison que tu n’avais pas prévue","L’attention est forte, mais elle attire aussi beaucoup de personnes hors cible."]],
TEAM:[
["Tu n’arrives plus à tout faire seul","Le produit, les ventes et le support se disputent ton temps."],
["Un excellent développeur senior veut rejoindre l’aventure","Il peut accélérer fortement le produit, mais son coût mensuel est important."],
["Une personne complémentaire te propose de devenir cofondateur","Tu gagnerais des compétences et du temps, mais tu céderais une partie du capital."],
["Tu commences à travailler beaucoup trop d’heures","La vitesse actuelle n’est probablement pas soutenable plusieurs mois."],
["Les leads augmentent mais personne ne fait vraiment de vente","Tu peux recruter, automatiser ou continuer à vendre toi-même."],
["Un candidat très fort veut travailler uniquement à distance","Le talent est là, mais tu dois adapter ton organisation."],
["Un salarié produit peu depuis plusieurs mois","Le garder évite une rupture, mais l’équipe absorbe son coût."],
["L’équipe demande des stock-options","Cela peut fidéliser les meilleurs, mais dilue légèrement les fondateurs."],
["Tu passes plus de temps à coordonner qu’à construire","La taille de l’équipe commence à nécessiter une vraie organisation."],
["Deux membres de l’équipe sont en conflit sur la direction produit","Le désaccord ralentit les décisions et commence à toucher l’ambiance."]],
FINANCE:[
["Un business angel veut investir maintenant","L’argent donne du runway, mais la valorisation est encore faible et la dilution coûte cher."],
["Ta trésorerie couvre moins de quatre mois de dépenses","Tu peux lever tôt, emprunter ou réduire le burn."],
["Ta banque propose un prêt professionnel","Tu gardes tes parts, mais la dette devra être remboursée même si la croissance ralentit."],
["Tu es éligible à une aide publique","Le dossier prend du temps, mais l’argent ne dilue pas ton capital."],
["Ton fournisseur cloud propose des crédits contre un engagement annuel","L’économie est réelle si tu restes chez lui, mais tu perds de la flexibilité."],
["Une grosse échéance fiscale approche","Le montant est prévisible mais peut casser ton rythme d’investissement."],
["Plusieurs clients paient leurs factures en retard","Le revenu existe sur le papier, mais le cash n’arrive pas assez vite."],
["Ton runway baisse alors que la croissance reste bonne","Tu dois décider si tu protèges la trésorerie ou si tu continues d’accélérer."],
["Un fonds te présente une term sheet agressive","Le chèque est gros, mais les conditions donnent beaucoup de pouvoir aux investisseurs."],
["Un investisseur existant propose un bridge très rapide","Tu peux sécuriser plusieurs mois de runway au prix d’une nouvelle dilution."]],
COMPETITION:[
["Un concurrent copie ta fonctionnalité principale","Ton avantage produit vient de se réduire brutalement."],
["Un concurrent baisse ses prix de 40 %","Les prospects commencent à comparer uniquement sur le prix."],
["Une grande entreprise annonce un produit proche du tien","Elle a plus de moyens, mais elle n’est pas encore spécialisée sur ta niche."],
["Le principal concurrent subit une panne publique","Des utilisateurs cherchent une alternative immédiatement."],
["Deux concurrents annoncent leur fusion","Ils deviennent plus gros, mais leur intégration risque de les ralentir."],
["Un concurrent publie une comparaison où il se présente comme meilleur","Le contenu circule chez plusieurs prospects."],
["Ton rival lance gratuitement une fonctionnalité que tu factures","Ta proposition de valeur est directement attaquée."],
["Un concurrent tente de débaucher ton meilleur client","Le client te demande ce que tu peux faire pour le garder."],
["Un nouvel entrant propose une offre freemium très généreuse","Il attire beaucoup d’utilisateurs, mais son modèle économique est encore flou."],
["Un concurrent te propose de racheter ta technologie","L’offre est sérieuse, mais accepter arrêterait ta trajectoire indépendante."]],
INFRA:[
["Les pages deviennent lentes aux heures de pointe","La croissance commence à révéler les limites de ton architecture."],
["Une panne de quelques minutes touche tes utilisateurs","L’incident reste limité, mais la confiance peut vite se dégrader."],
["La base de données devient le principal goulot d’étranglement","Chaque nouveau client augmente le risque d’incident."],
["Un audit découvre une faille de sécurité potentielle","Aucune donnée n’a fui, mais le risque est désormais connu."],
["Tu réalises que tes sauvegardes n’ont jamais été réellement restaurées","Elles existent, mais tu ne sais pas si elles fonctionneraient en cas de catastrophe."],
["Ton fournisseur cloud augmente fortement ses tarifs","Rester est simple, migrer est coûteux mais peut réduire les dépenses futures."],
["Des clients atteignent régulièrement les limites de ton API","Le produit fonctionne, mais les usages avancés deviennent frustrants."],
["Un service externe critique annonce une hausse de prix","Ton produit en dépend fortement et le remplacer prendrait du temps."],
["Tes données deviennent difficiles à analyser","Tu prends des décisions avec des tableaux incomplets et plusieurs sources contradictoires."],
["L’architecture actuelle ne pourra pas supporter dix fois plus d’utilisateurs","Tu n’as pas encore ce trafic, mais attendre peut rendre la migration dangereuse."]],
REPUTATION:[
["Un avis très négatif devient visible sur les réseaux","Le client est mécontent et d’autres utilisateurs commencent à réagir."],
["Un expert reconnu recommande publiquement ton produit","La crédibilité gagnée peut être exploitée immédiatement."],
["Le support met plusieurs jours à répondre","Le volume de demandes augmente plus vite que ta capacité de réponse."],
["Tu as publiquement promis une fonctionnalité en retard","Les utilisateurs commencent à demander des comptes."],
["Un utilisateur accuse ton produit de collecter trop de données","L’accusation est exagérée, mais le sujet est sensible."],
["Une vague de demandes de remboursement arrive après une mise à jour","Le problème semble concentré sur un segment précis."],
["Ta communauté critique une décision de pricing","Le changement est rentable sur le papier mais perçu comme brutal."],
["Un membre de l’équipe publie un message maladroit depuis son compte personnel","Le message est associé à la marque alors qu’il ne représente pas officiellement l’entreprise."],
["Un journaliste veut t’interviewer sur ta croissance","L’exposition peut aider, mais une mauvaise déclaration restera publique."],
["Ton produit reçoit un prix dans une petite conférence","Le prix est réel, mais sa valeur dépend de ce que tu en fais commercialement."]],
LEGAL:[
["Un client européen demande des garanties RGPD précises","La demande est raisonnable mais nécessite du travail documentaire."],
["Tes conditions d’utilisation datent du lancement","Le produit et le modèle ont beaucoup changé depuis."],
["Une autre société utilise un nom très proche du tien","Le risque de confusion grandit à mesure que ta marque devient visible."],
["Un freelance a développé une partie critique sans clause de cession claire","Le code fonctionne, mais la propriété intellectuelle est mal documentée."],
["Un grand compte exige un accord de traitement des données","Sans document sérieux, la vente risque de s’arrêter."],
["Un client demande un SLA avec pénalités financières","Le contrat est rentable, mais une panne pourrait devenir coûteuse."],
["Ton premier salarié arrive et tes contrats sont encore très simples","Les règles informelles ne suffisent plus vraiment."],
["Tu commences à vendre dans plusieurs pays européens","La TVA et la facturation deviennent plus complexes."],
["Une administration te demande des preuves d’accessibilité","Le produit n’est pas totalement conforme mais plusieurs corrections sont possibles."],
["Une librairie essentielle change de licence","Continuer sans vérifier peut créer un risque juridique futur."]],
STRATEGY:[
["Une niche précise convertit deux fois mieux que le reste du marché","Tu peux te spécialiser ou continuer à viser large."],
["Des utilisateurs particuliers arrivent alors que tu vendais surtout aux entreprises","Le nouveau segment grandit vite mais demande un produit différent."],
["Des partenaires veulent construire des services autour de ton produit","Tu peux devenir une plateforme ou rester un produit fermé."],
["Plusieurs clients demandent une API publique","L’API peut accélérer l’écosystème, mais elle augmente la complexité technique."],
["Un marché étranger montre des signes de traction sans marketing","L’opportunité existe mais demande localisation et support."],
["Tes ventes stagnent depuis plusieurs mois","Tu peux pivoter fortement ou améliorer patiemment ce qui existe."],
["Une société plus grande propose de racheter ta startup","L’offre te donne une sortie immédiate mais met fin à la course au milliard."],
["Tu peux continuer en bootstrap ou préparer une vraie levée","Les deux chemins changent profondément le niveau de risque et de contrôle."],
["Les clients annuels restent beaucoup plus longtemps","Tu peux pousser l’abonnement annuel au prix d’une remise."],
["Un segment de clients est clairement plus rentable que les autres","Concentrer le produit peut améliorer l’économie mais fermer certaines portes."]]
};

const LABELS={
PRODUCT:[["Refaire l’onboarding","Ajouter des astuces sans tout refaire","Laisser encore un mois"],["Construire la demande du client","Proposer une version générique","Refuser la demande"],["Lancer une app mobile","Améliorer le web mobile","Attendre plus de preuves"],["Faire un sprint qualité","Corriger seulement les bugs critiques","Continuer la roadmap"],["Construire la fonctionnalité IA","Faire un prototype limité","Ignorer la mode"],["Construire l’intégration la plus demandée","Créer un système générique","Dire non aux intégrations"],["Limiter l’offre gratuite","Optimiser les coûts du gratuit","Ne rien changer"],["Rembourser la dette technique","Refactorer progressivement","Continuer à livrer vite"],["Corriger l’accessibilité maintenant","Traiter les problèmes principaux","Reporter"],["Couper la roadmap de moitié","Prioriser avec les clients","Garder toutes les idées"]],
SALES:[["Faire un pilote payant","Accepter un pilote gratuit court","Refuser le pilote"],["Accepter avec 15 % de remise","Négocier 5 % de remise","Refuser la remise"],["Remplir le questionnaire","Proposer un appel sécurité","Abandonner le deal"],["Signer avec l’agence","Tester sur 3 clients","Rester en vente directe"],["Corriger les deux irritants","Proposer un retour sans promesse","Ne pas courir après ce client"],["Signer et adapter le support","Passer par un partenaire local","Attendre"],["Accorder les conditions achats","Demander un acompte","Quitter le deal"],["Créer une offre premium","Tester le service sur 3 clients","Rester 100 % self-service"],["Pilote gratuit contre étude de cas","Pilote payant à prix réduit","Refuser le logo gratuit"],["Sécuriser le grand client","Réduire progressivement la dépendance","Refuser de grossir ce compte"]],
MARKETING:[["Booster la publication","Contacter le créateur","Laisser l’organique agir"],["Couper les campagnes faibles","Tester de nouvelles audiences","Continuer au même budget"],["Produire une série d’articles","Optimiser seulement cet article","Revenir au produit"],["Acheter le sponsoring","Négocier un test moins cher","Passer"],["Lancer le parrainage","Tester sur les meilleurs clients","Garder le bouche-à-oreille naturel"],["Préparer un vrai lancement","Publier sans campagne payante","Attendre"],["Prendre un petit stand","Acheter seulement des rendez-vous","Ne pas y aller"],["Repositionner la marque","Tester deux nouveaux messages","Ne rien changer"],["Créer un programme communauté","Nommer quelques ambassadeurs","Observer sans intervenir"],["Monétiser immédiatement la viralité","Filtrer le trafic vers la bonne cible","Profiter sans investir"]],
TEAM:[["Recruter un généraliste","Prendre un freelance","Continuer seul"],["Recruter le senior","Proposer une mission de 3 mois","Refuser le coût"],["Accepter un cofondateur","Tester la collaboration avant","Rester seul au capital"],["Lever le pied un mois","Déléguer une partie du travail","Continuer au même rythme"],["Recruter un commercial","Mettre en place un CRM et automatiser","Continuer à vendre toi-même"],["Recruter en remote","Proposer une période d’essai courte","Chercher quelqu’un sur place"],["Faire un plan de progrès","Se séparer rapidement","Attendre encore"],["Créer un pool de stock-options","Donner des primes cash","Ne rien changer"],["Nommer un responsable","Réduire le nombre de projets","Continuer sans management"],["Trancher toi-même","Organiser une décision structurée","Laisser l’équipe résoudre seule"]],
FINANCE:[["Lever maintenant","Négocier un petit ticket","Rester bootstrap"],["Chercher un bridge","Prendre une dette courte","Couper les dépenses"],["Prendre le prêt","Négocier une ligne plus petite","Refuser toute dette"],["Monter le dossier","Payer un expert pour le dossier","Ignorer l’aide"],["Signer l’engagement cloud","Négocier un engagement plus court","Garder la flexibilité"],["Payer immédiatement","Négocier un échéancier","Reporter et prendre le risque"],["Relancer fortement les clients","Offrir une remise pour paiement immédiat","Attendre les paiements"],["Réduire le burn","Lever pendant que les métriques sont bonnes","Continuer à accélérer"],["Accepter la term sheet","Négocier les clauses","Refuser le fonds"],["Prendre le bridge","Lever un peu plus mais plus lentement","Réduire brutalement le burn"]],
COMPETITION:[["Accélérer le produit","Se différencier sur un segment","Ne pas réagir"],["Baisser aussi les prix","Ajouter de la valeur sans baisser","Laisser passer la guerre des prix"],["Se spécialiser fortement","Accélérer le marketing","Attendre de voir"],["Cibler leurs utilisateurs mécontents","Publier une comparaison factuelle","Ne pas profiter de leur panne"],["Attaquer pendant leur intégration","Se rapprocher d’un partenaire","Rester concentré"],["Répondre avec ta propre comparaison","Contacter directement les prospects","Ignorer le contenu"],["Rendre la fonctionnalité gratuite","Créer une version premium supérieure","Conserver ton pricing"],["Faire un geste commercial","Renforcer la relation produit","Accepter de perdre le client"],["Lancer une offre gratuite limitée","Doubler sur les clients payants","Ignorer leur freemium"],["Négocier une vente","Proposer un partenariat","Refuser et continuer seul"]],
INFRA:[["Augmenter la capacité","Optimiser les requêtes","Accepter la lenteur"],["Faire une revue d’incident","Ajouter de la redondance","Minimiser l’incident"],["Migrer la base","Optimiser l’existant","Repousser"],["Corriger la faille immédiatement","Faire auditer le périmètre","Prendre le risque"],["Tester une restauration complète","Ajouter une seconde sauvegarde","Faire confiance aux sauvegardes"],["Migrer vers un autre fournisseur","Optimiser les ressources actuelles","Absorber la hausse"],["Augmenter les limites API","Créer des plans d’usage","Ne rien changer"],["Remplacer le service","Négocier le contrat","Payer la hausse"],["Construire un vrai suivi data","Nettoyer seulement les métriques clés","Continuer avec les tableaux actuels"],["Repenser l’architecture maintenant","Préparer un plan de migration","Attendre d’être obligé"]],
REPUTATION:[["Répondre publiquement et résoudre","Contacter le client en privé","Ignorer l’avis"],["Transformer la recommandation en étude de cas","Demander une citation officielle","Ne rien exploiter"],["Renforcer le support","Créer une base de connaissances","Accepter les délais"],["Publier un nouveau calendrier réaliste","Livrer une version minimale vite","Ne plus communiquer de date"],["Publier une explication transparente","Faire un audit rapide","Ignorer l’accusation"],["Rembourser largement","Corriger uniquement le segment touché","Contester les remboursements"],["Revenir partiellement sur le pricing","Expliquer la hausse avec des données","Maintenir sans répondre"],["Prendre publiquement ses distances","Parler d’abord avec l’employé","Ignorer le message"],["Accepter l’interview","Préparer les messages avec soin","Refuser la presse"],["Utiliser le prix dans les ventes","Communiquer modestement","Ne rien changer"]],
LEGAL:[["Mettre la conformité à niveau","Faire le minimum demandé","Refuser les exigences"],["Réécrire les conditions","Faire une révision légère","Attendre"],["Déposer la marque","Négocier avec l’autre société","Ignorer le risque"],["Faire signer une cession","Réécrire le module concerné","Ne rien faire"],["Préparer un DPA solide","Envoyer un modèle simple","Abandonner le grand compte"],["Accepter le SLA","Négocier des limites de responsabilité","Refuser le SLA"],["Faire des contrats complets","Utiliser un modèle simple","Continuer informellement"],["Automatiser TVA et facturation","Prendre un comptable","Gérer manuellement"],["Corriger les points majeurs","Lancer un audit complet","Contester la demande"],["Remplacer la librairie","Acheter une licence","Continuer sans vérifier"]],
STRATEGY:[["Se spécialiser sur la niche","Créer une offre dédiée sans abandonner le reste","Continuer à viser large"],["Ouvrir une offre grand public","Garder le B2B et tester doucement","Refuser le nouveau segment"],["Ouvrir la plateforme","Créer quelques intégrations partenaires","Rester fermé"],["Construire l’API publique","Faire une API privée pour quelques clients","Reporter"],["Entrer sur ce marché","Tester avec une page localisée","Rester sur le marché actuel"],["Pivoter franchement","Changer seulement le positionnement","Continuer sans changement"],["Vendre la startup","Négocier un prix supérieur","Refuser l’offre"],["Préparer une levée","Rester bootstrap","Chercher seulement des aides non dilutives"],["Pousser l’annuel","Proposer annuel et mensuel","Garder le mensuel"],["Se concentrer sur le segment rentable","Créer une équipe dédiée","Servir tous les segments"]]
};

function spend(s,n){s.cash-=Math.round(n)}
function chance(p,onSuccess,onFail){if(Math.random()<p){onSuccess();return "Le pari a fonctionné ce mois-ci."}onFail();return "Le pari n’a pas fonctionné comme prévu ce mois-ci."}
function makeChoices(category,i){const L=LABELS[category][i],k=1+i*.12;
if(category==="PRODUCT"){const cost=Math.round(180*k);return[
{label:L[0],hint:`-${fmtMoney(cost)} maintenant · amélioration produit durable`,cost,good:"Tu investis dans la valeur du produit, ce qui réduit le churn et soutient la conversion dans la durée.",bad:"Tu consommes du cash aujourd’hui et tu retardes d’autres opportunités de croissance.",apply:s=>{spend(s,cost);s.product+=6+i*.35;s.reputation+=1;return "La qualité du produit progresse nettement."}},
{label:L[1],hint:"Option intermédiaire · effet plus rapide mais moins profond",cost:0,good:"Tu obtiens un bénéfice visible rapidement sans immobiliser beaucoup de trésorerie.",bad:"Le problème de fond peut revenir plus tard et coûter davantage.",apply:s=>{s.product+=3;s.conversion+=.002;return chance(.72,()=>s.reputation+=2,()=>s.reputation-=2)}},
{label:L[2],hint:"0 € · cash préservé · risque de retard produit",cost:0,good:"Tu protèges ta trésorerie et gardes la possibilité d’investir ailleurs.",bad:"Le produit accumule du retard et peut perdre en réputation ou en conversion.",apply:s=>{s.product-=1.5;s.growth-=.002;return "Tu préserves le cash, mais le problème reste ouvert."}}]}
if(category==="SALES"){const value=Math.round(450+260*i);return[
{label:L[0],hint:`Cash potentiel +${fmtMoney(value)} · demande du temps produit`,cost:0,good:"Tu transformes une opportunité commerciale en cash et en preuve de marché.",bad:"Servir ce client peut détourner le produit ou créer des attentes spécifiques.",apply:s=>{s.cash+=value;s.customers+=Math.max(1,Math.round(1+i/3));s.product-=1;return chance(.78,()=>s.reputation+=3,()=>s.reputation-=2)}},
{label:L[1],hint:"Compromis commercial · meilleure conversion · marge un peu plus faible",cost:0,good:"Tu réduis le risque de perdre le deal tout en évitant de tout sacrifier.",bad:"Les concessions commerciales deviennent vite une habitude et peuvent tirer le prix vers le bas.",apply:s=>{s.conversion+=.004;s.price=Math.max(6,s.price*.97);s.reputation+=1;return "Le compromis améliore légèrement la conversion."}},
{label:L[2],hint:"0 € · protège le focus · opportunité perdue",cost:0,good:"Tu protèges la roadmap et évites un client potentiellement coûteux à servir.",bad:"Tu renonces à du revenu et à une occasion d’apprendre du marché.",apply:s=>{s.product+=2;s.reputation-=.5;return "Tu gardes le focus, mais le revenu immédiat disparaît."}}]}
if(category==="MARKETING"){const cost=Math.round(160+120*i);return[
{label:L[0],hint:`-${fmtMoney(cost)} · croissance potentielle forte · résultat incertain`,cost,good:"Tu profites d’un signal de marché pendant qu’il est chaud.",bad:"L’acquisition payante peut brûler du cash sans créer de clients rentables.",apply:s=>{spend(s,cost);return chance(.68,()=>{s.users*=1.10+i*.008;s.reputation+=2},()=>{s.users*=1.02;s.reputation-=1})}},
{label:L[1],hint:"Investissement modéré · apprentissage marketing",cost:Math.round(cost*.45),good:"Tu achètes de l’apprentissage sans engager un budget trop important.",bad:"L’effet sera plus lent et peut être trop faible pour créer un vrai avantage.",apply:s=>{spend(s,cost*.45);s.users*=1.05;s.growth+=.004;s.conversion+=.001;return "Le test produit un signal exploitable sans trop entamer le runway."}},
{label:L[2],hint:"0 € · cash préservé · croissance plus organique",cost:0,good:"Tu gardes ton runway pour le produit et les ventes.",bad:"Tu peux laisser passer une fenêtre d’attention que les concurrents exploiteront.",apply:s=>{s.growth+=.001;s.product+=.5;return "La croissance reste plus lente mais financièrement saine."}}]}
if(category==="TEAM"){const hireCost=Math.round(550+80*i);return[
{label:L[0],hint:`-${fmtMoney(hireCost)} maintenant · coût mensuel supplémentaire possible`,cost:hireCost,good:"Tu ajoutes de la capacité durable et réduis les goulots d’étranglement du fondateur.",bad:"Chaque recrutement augmente le burn et rend la société moins flexible.",apply:s=>{spend(s,hireCost);if(i===2){s.equity*=.90;s.team+=1;s.product+=6;s.growth+=.008;return "Tu gagnes un partenaire durable, mais tu cèdes 10 % du capital."}s.employees+=1;s.team+=1;s.product+=5;s.reputation+=1;return "La capacité de l’équipe augmente, avec un nouveau coût fixe mensuel."}},
{label:L[1],hint:`-${fmtMoney(Math.round(hireCost*.45))} · solution temporaire`,cost:Math.round(hireCost*.45),good:"Tu résous une partie du problème sans ajouter immédiatement un gros coût fixe.",bad:"La solution temporaire crée moins de capital organisationnel et peut coûter cher si elle dure.",apply:s=>{spend(s,hireCost*.45);s.product+=3;s.growth+=.002;return "Tu achètes de la capacité à court terme sans alourdir fortement la masse salariale."}},
{label:L[2],hint:"0 € · cash préservé · pression sur l’équipe",cost:0,good:"Tu gardes des coûts fixes faibles et du runway.",bad:"Les goulots d’étranglement restent présents et peuvent ralentir le produit ou la vente.",apply:s=>{s.product-=1;s.reputation-=.5;return "Tu protèges le cash, mais la capacité de l’équipe ne progresse pas."}}]}
if(category==="FINANCE")return[
{label:L[0],hint:"Plus de cash · dilution du capital",cost:0,good:"Tu sécurises du runway et peux investir avant que la situation devienne urgente.",bad:"Lever tôt coûte des parts et peut réduire fortement ta valeur personnelle à long terme.",apply:s=>{const amount=Math.round(clamp(s.valuation*(.16+i*.018),2500,220000)),dilution=clamp(.06+i*.009,.06,.15);s.cash+=amount;s.equity*=1-dilution;s.totalRaised+=amount;s.reputation+=1;return `Tu lèves ${fmtMoney(amount)} contre ${(dilution*100).toFixed(0)} % de dilution.`}},
{label:L[1],hint:"Cash sans dilution · dette et coût financier",cost:0,good:"Tu conserves davantage de capital si la société continue de croître.",bad:"La dette reste due même si les ventes ralentissent et augmente les dépenses mensuelles.",apply:s=>{const amount=Math.round(clamp(s.valuation*(.08+i*.01),1500,100000));s.cash+=amount;s.debt+=amount;s.reputation-=1;return `Tu ajoutes ${fmtMoney(amount)} de dette au bilan.`}},
{label:L[2],hint:"Pas de financement · discipline de coûts",cost:0,good:"Tu évites dilution et dette et forces une meilleure discipline économique.",bad:"Moins de ressources peut ralentir la croissance au moment où le marché est disponible.",apply:s=>{s.marketing=Math.round(s.marketing*.55);s.growth-=.003;s.product+=1;return "Le burn diminue, mais tu sacrifies une partie de la vitesse."}}];
if(category==="COMPETITION"){const cost=Math.round(350+220*i);return[
{label:L[0],hint:`-${fmtMoney(cost)} · produit/réputation renforcés`,cost,good:"Tu réponds par un avantage que le concurrent devra lui aussi reproduire.",bad:"Réagir à chaque mouvement adverse peut te faire perdre ta propre stratégie.",apply:s=>{spend(s,cost);s.product+=5+i*.25;s.reputation+=2;return "La différenciation produit s’améliore."}},
{label:L[1],hint:"Réponse commerciale · conversion améliorée",cost:0,good:"Tu adaptes ton offre au terrain réel plutôt que d’ignorer la pression.",bad:"Une guerre de prix ou de promotions peut détériorer l’économie du produit.",apply:s=>{s.price=Math.max(6,s.price*.94);s.conversion+=.005;s.growth+=.002;return "La conversion progresse, mais le revenu par client baisse légèrement."}},
{label:L[2],hint:"0 € · focus interne · risque de perte de terrain",cost:0,good:"Tu évites de piloter ta société uniquement en réaction aux concurrents.",bad:"Si la menace est réelle, l’inaction peut coûter des utilisateurs et de la réputation.",apply:s=>chance(.55,()=>{s.product+=2;s.reputation+=1},()=>{s.users*=.95;s.reputation-=3})}]}
if(category==="INFRA"){const cost=Math.round(300+210*i);return[
{label:L[0],hint:`-${fmtMoney(cost)} · capacité et fiabilité améliorées`,cost,good:"Tu réduis le risque qu’une croissance future se transforme en panne.",bad:"Tu dépenses avant que toute la capacité supplémentaire soit nécessaire.",apply:s=>{spend(s,cost);s.infraLevel+=1;s.product+=2;s.reputation+=2;return "La capacité technique augmente et le risque opérationnel baisse."}},
{label:L[1],hint:`-${fmtMoney(Math.round(cost*.4))} · coûts techniques optimisés`,cost:Math.round(cost*.4),good:"Tu obtiens une partie du bénéfice sans financer une grosse migration.",bad:"L’optimisation a une limite et peut simplement repousser un investissement inévitable.",apply:s=>{spend(s,cost*.4);s.infraEfficiency=clamp(s.infraEfficiency*.92,.55,1);s.product+=1;return "Les coûts variables d’infrastructure diminuent."}},
{label:L[2],hint:"0 € · risque d’incident",cost:0,good:"Tu préserves le cash tant que l’infrastructure tient.",bad:"Une panne peut faire perdre des utilisateurs et coûter beaucoup plus cher que la prévention.",apply:s=>chance(.62,()=>{s.reputation-=.5},()=>{s.users*=.90;s.reputation-=7;s.product-=2})}]}
if(category==="REPUTATION"){const cost=Math.round(90+80*i);return[
{label:L[0],hint:`-${fmtMoney(cost)} · réputation renforcée`,cost,good:"Une réponse visible montre que l’entreprise prend le problème au sérieux.",bad:"Une communication forte crée aussi une promesse publique qu’il faudra tenir.",apply:s=>{spend(s,cost);s.reputation+=7;s.product+=1;return "La réponse est bien reçue et restaure une partie de la confiance."}},
{label:L[1],hint:"Réponse ciblée · effet modéré",cost:0,good:"Tu traites le cœur du problème sans sur-réagir publiquement.",bad:"Le reste du marché peut ne jamais voir que le problème a été corrigé.",apply:s=>{s.reputation+=3;s.conversion+=.002;return "La situation s’améliore, mais l’effet reste limité."}},
{label:L[2],hint:"0 € · résultat incertain",cost:0,good:"Tu évites d’amplifier un sujet qui pourrait disparaître seul.",bad:"Le silence peut être interprété comme du mépris si la critique continue.",apply:s=>chance(.52,()=>s.reputation+=1,()=>{s.reputation-=6;s.growth-=.004})}]}
if(category==="LEGAL"){const cost=Math.round(220+160*i);return[
{label:L[0],hint:`-${fmtMoney(cost)} · conformité fortement améliorée`,cost,good:"Tu réduis un risque qui pourrait devenir très coûteux quand la société grossit.",bad:"Le travail juridique consomme du cash sans créer directement de nouveaux clients.",apply:s=>{spend(s,cost);s.compliance=clamp(s.compliance+10,0,100);s.reputation+=2;return "Le risque juridique baisse nettement."}},
{label:L[1],hint:`-${fmtMoney(Math.round(cost*.35))} · correction partielle`,cost:Math.round(cost*.35),good:"Tu règles les points les plus urgents avec un coût limité.",bad:"La zone grise restante peut réapparaître lors d’une vente ou d’un audit.",apply:s=>{spend(s,cost*.35);s.compliance=clamp(s.compliance+4,0,100);return "Le risque baisse, mais n’est pas complètement éliminé."}},
{label:L[2],hint:"0 € · risque futur",cost:0,good:"Tu gardes les ressources concentrées sur la croissance immédiate.",bad:"Le problème peut se transformer plus tard en amende, perte de contrat ou crise de réputation.",apply:s=>chance(.68,()=>s.compliance-=1,()=>{const fine=Math.round(300+250*i);spend(s,fine);s.reputation-=5;s.compliance-=6})}]}
if(category==="STRATEGY"){if(i===6)return[
{label:L[0],hint:"Fin immédiate : sortie par acquisition",cost:0,good:"Tu transformes une valorisation théorique en sortie réelle et réduis le risque futur.",bad:"Tu abandonnes la possibilité d’atteindre une valorisation beaucoup plus élevée.",apply:s=>{s.flags.acquired=true;s.flags.exitPrice=Math.round(s.valuation*1.25);return `L’acquéreur accepte une transaction à ${fmtMoney(s.flags.exitPrice)}.`}},
{label:L[1],hint:"Tente d’obtenir +40 % · risque de perdre l’offre",cost:0,good:"Négocier peut augmenter fortement la valeur de sortie sans construire un mois de plus.",bad:"Une négociation agressive peut faire disparaître l’acquéreur.",apply:s=>chance(.55,()=>{s.flags.acquired=true;s.flags.exitPrice=Math.round(s.valuation*1.55)},()=>{s.reputation-=2})},
{label:L[2],hint:"Continuer indépendant",cost:0,good:"Tu conserves tout le potentiel futur de la société.",bad:"Tu refuses une liquidité certaine pour un résultat futur incertain.",apply:s=>{s.reputation+=2;s.growth+=.004;return "Tu refuses l’offre et continues la course au milliard."}}];return[
{label:L[0],hint:"Choix offensif · croissance plus rapide · plus de risque",cost:0,good:"Une stratégie claire concentre les ressources et peut créer un avantage difficile à rattraper.",bad:"Un choix fort ferme des options et peut être douloureux si l’hypothèse est mauvaise.",apply:s=>{s.users*=1.08+i*.006;s.growth+=.007;s.product-=1;return "La société devient plus offensive et plus concentrée."}},
{label:L[1],hint:"Test progressif · apprentissage · risque modéré",cost:0,good:"Tu obtiens des données avant de rendre la décision irréversible.",bad:"Tester lentement peut laisser un concurrent prendre la fenêtre de marché.",apply:s=>{s.product+=2;s.conversion+=.003;s.growth+=.002;return "Le test améliore la qualité des décisions sans bouleverser la société."}},
{label:L[2],hint:"Conserver la trajectoire actuelle",cost:0,good:"Tu évites une dispersion et gardes l’équipe concentrée.",bad:"La stabilité devient un défaut si le marché est réellement en train de changer.",apply:s=>{s.product+=1;s.growth-=.001;return "La trajectoire reste stable, avec moins de risque mais moins d’optionnalité."}}]}}

function categoryCondition(category,i,s){if(category==="PRODUCT")return s.month>=1+Math.floor(i/4);if(category==="SALES")return s.month>=2&&s.customers>=Math.min(4+i*2,20);if(category==="MARKETING")return s.month>=2;if(category==="TEAM")return s.month>=3;if(category==="FINANCE")return s.month>=3;if(category==="COMPETITION")return s.month>=4&&s.users>=Math.min(120+i*90,900);if(category==="INFRA")return s.month>=4&&s.users>=Math.min(180+i*120,1200);if(category==="REPUTATION")return s.month>=3;if(category==="LEGAL")return s.month>=4;return s.month>=2}
const events=Object.entries(SCENARIO_BANK).flatMap(([category,items])=>items.map(([title,description],i)=>({id:`${category.toLowerCase()}-${i+1}`,category,risk:["Faible","Modéré","Élevé"][i%3],title,description,condition:s=>categoryCondition(category,i,s),choices:makeChoices(category,i)})));
console.assert(events.length===100,`La bibliothèque doit contenir 100 événements, trouvé : ${events.length}`);

function expenseBreakdown(){const salaries=state.employees*state.salaryPerEmployee,infra=Math.round((120+state.infraLevel*80+state.users*.02)*state.infraEfficiency),marketing=state.marketing,debtCost=Math.round(state.debt*.02);return{salaries,infra,marketing,debtCost,total:salaries+infra+marketing+debtCost}}
function recalcEconomy(){state.product=clamp(state.product,5,100);state.reputation=clamp(state.reputation,0,100);state.compliance=clamp(state.compliance,0,100);state.conversion=clamp(state.conversion,.01,.22);state.growth=clamp(state.growth,.005,.55);const pf=.55+state.product/100,rf=.65+state.reputation/140,tf=1+Math.log2(Math.max(1,state.team))*.08,marketingUsers=state.marketing*(.65+state.reputation/100),organic=state.users*state.growth*pf*rf*tf,churn=state.users*clamp(.09-state.product*.00055-state.reputation*.00025,.012,.10);state.users=Math.max(30,Math.round(state.users+organic+marketingUsers-churn));const pricePenalty=Math.max(.45,1-(state.price-12)*.012),effective=clamp(state.conversion*pricePenalty*(.7+state.product/125),.01,.25);state.customers=Math.max(1,Math.round(state.users*effective));state.revenue=Math.round(state.customers*state.price);const b=expenseBreakdown();state.expenses=Math.round(b.total);state.profit=state.revenue-state.expenses;state.cash+=state.profit;const annual=state.revenue*12,gp=2.1+state.growth*8,qp=(.65+state.product/180)*(.7+state.reputation/200),pb=state.profit>0?1.18:.86;state.valuation=Math.max(1000,Math.round(annual*gp*qp*pb+Math.max(0,state.cash)*.55-state.debt*.35))}
function recalcSnapshotOnly(){state.revenue=Math.round(state.customers*state.price);state.expenses=Math.round(expenseBreakdown().total);state.profit=state.revenue-state.expenses;const annual=state.revenue*12;state.valuation=Math.max(1000,Math.round(annual*(2.1+state.growth*8)*(.65+state.product/180)*(.7+state.reputation/200)*.86+Math.max(0,state.cash)*.55-state.debt*.35))}
function getAvailableEvents(){const unseen=events.filter(e=>!state.flags.seen[e.id]);let contextual=unseen.filter(e=>e.condition(state));if(contextual.length>1&&state.lastCategory){const other=contextual.filter(e=>e.category!==state.lastCategory);if(other.length)contextual=other}if(contextual.length)return contextual;const unlocked=unseen.filter(e=>{const n=Number(e.id.split("-").pop())-1;return categoryCondition(e.category,Math.max(0,n),{...state,users:Math.max(state.users,1200),customers:Math.max(state.customers,30)})});return unlocked.length?unlocked:unseen}
function pickEvent(){const pool=getAvailableEvents();if(!pool.length){state.flags.seen={};state.flags.seenCount=0;return pickEvent()}const e=pool[Math.floor(Math.random()*pool.length)];state.flags.seen[e.id]=true;state.flags.seenCount++;state.lastCategory=e.category;return e}
function resetGame(){state=JSON.parse(JSON.stringify(START));recalcSnapshotOnly();pushHistory();pendingEnd=null;awaitingContinue=false;$('start-screen').classList.add('hidden');$('end-screen').classList.add('hidden');$('game-screen').classList.remove('hidden');$('feed').innerHTML='';addFeed('Mois 1',`Départ : ${fmtMoney(state.cash)} de cash, aucun salarié, ${fmtMoney(state.expenses)}/mois de coûts techniques.`);render();showEvent()}
function financingEvent(){const need=Math.max(1000,Math.ceil(Math.abs(state.cash)+state.expenses*2)),bridge=Math.round(Math.min(Math.max(2500,need),Math.max(2500,state.valuation*.35)));return{id:`rescue-${state.month}`,category:'FINANCE',risk:'Trésorerie critique',title:'Ta trésorerie est négative, mais la startup a encore de la valeur',description:`Tu as ${fmtMoney(state.cash)} de cash pour une valorisation de ${fmtMoney(state.valuation)}. Trouve du financement ou arrête.`,choices:[{label:'Bridge investisseur',hint:`+${fmtMoney(bridge)} · dilution 12 %`,cost:0,good:"Tu évites la faillite immédiate et achètes du runway.",bad:"Cette urgence te force à accepter une dilution défavorable.",apply:s=>{s.cash+=bridge;s.equity*=.88;s.totalRaised+=bridge;return "Le bridge te redonne de la trésorerie."}},{label:'Dette court terme',hint:`+${fmtMoney(bridge)} · dette +${fmtMoney(bridge)}`,cost:0,good:"Tu conserves davantage de capital.",bad:"Le coût de la dette augmente ton burn et reporte le risque.",apply:s=>{s.cash+=bridge;s.debt+=bridge;return "La dette évite la faillite, mais augmente les charges financières."}},{label:'Arrêter la société',hint:'Fin de la run',cost:0,quit:true,good:"Tu limites les pertes supplémentaires.",bad:"Tu abandonnes toute valeur future de la société.",apply:()=>""}]}}
function snapshot(){return{cash:state.cash,revenue:state.revenue,expenses:state.expenses,profit:state.profit,users:state.users,customers:state.customers,valuation:state.valuation,reputation:state.reputation,product:state.product,equity:state.equity,debt:state.debt}}
function deltaText(before){const pairs=[["Cash",state.cash-before.cash,fmtMoney],["CA/mois",state.revenue-before.revenue,fmtMoney],["Utilisateurs",state.users-before.users,fmt],["Valorisation",state.valuation-before.valuation,fmtMoney],["Réputation",state.reputation-before.reputation,n=>`${n.toFixed(0)} pts`],["Produit",state.product-before.product,n=>`${n.toFixed(0)} pts`]].filter(([,d])=>Math.abs(d)>.49);return pairs.slice(0,4).map(([label,d,f])=>`${d>=0?"+":""}${f(d)} ${label}`).join(" · ")||"Impact immédiat limité"}
function chooseCost(choice){return typeof choice.cost==="function"?choice.cost(state):(choice.cost||0)}
function choose(choice){const cost=chooseCost(choice);if(cost>state.cash)return;if(choice.quit){pendingEnd={won:false,reason:'cash'};return renderFeedback(choice,"Tu choisis de fermer la société.",snapshot())}const before=snapshot(),outcome=choice.apply(state)||"La décision est appliquée.";state.month++;recalcEconomy();pushHistory();addFeed('Mois '+state.month,`${choice.label} — ${monthlySummary()}`);render();pendingEnd=detectEnd();renderFeedback(choice,outcome,before)}
function detectEnd(){if(state.flags.acquired)return{won:true,reason:'acquisition'};if(state.equity<=.04)return{won:false,reason:'founder'};if(state.reputation<=0)return{won:false,reason:'reputation'};if(state.valuation>=1e9)return{won:true,reason:'win'};if(state.cash<0&&(state.debt>state.valuation*.65||state.reputation<20))return{won:false,reason:'cash'};if(state.month>96){if(state.profit>0&&state.revenue>=10000)return{won:true,reason:'profitable'};return{won:false,reason:'time'}}return null}
function renderFeedback(choice,outcome,before){awaitingContinue=true;$('event-category').textContent='DÉBRIEF';$('event-risk').textContent=`Décision prise · mois ${state.month}`;$('event-title').textContent=choice.label;$('event-description').textContent=outcome;const deltas=deltaText(before);$('choices').innerHTML=`<div class="decision-feedback"><div class="feedback-impact"><span>IMPACT DU MOIS</span><strong>${deltas}</strong></div><div class="feedback-grid"><div class="feedback-good"><b>✓ Ce qui était bon</b><p>${choice.good||"Cette décision avait un avantage réel dans ce contexte."}</p></div><div class="feedback-bad"><b>⚠ Ce qui pouvait mal tourner</b><p>${choice.bad||"Cette décision comportait aussi une contrepartie."}</p></div></div><button id="continue-btn" class="primary-btn">${pendingEnd?'Voir la fin':'Continuer'}</button></div>`;$('continue-btn').addEventListener('click',continueAfterFeedback)}
function continueAfterFeedback(){awaitingContinue=false;if(pendingEnd){const e=pendingEnd;pendingEnd=null;return endGame(e.won,e.reason)}if(state.cash<0){if(state.valuation>=Math.max(2500,Math.abs(state.cash)*2)&&state.reputation>=20){currentEvent=financingEvent();return renderCurrentEvent()}return endGame(false,'cash')}showEvent()}
function monthlySummary(){const b=expenseBreakdown(),p=state.profit>=0?`+${fmtMoney(state.profit)}`:fmtMoney(state.profit);return `${fmt(state.customers)} clients · CA ${fmtMoney(state.revenue)} · coûts ${fmtMoney(state.expenses)} (salaires ${fmtMoney(b.salaries)}, infra ${fmtMoney(b.infra)}, marketing ${fmtMoney(b.marketing)}, dette ${fmtMoney(b.debtCost)}) · résultat ${p}.`}
function renderCurrentEvent(){const e=currentEvent;$('event-title').textContent=e.title;$('event-description').textContent=e.description;$('event-category').textContent=e.category;$('event-risk').textContent=`Risque ${e.risk} · ${Math.min(state.flags.seenCount,100)}/100 vues`;$('choices').innerHTML='';e.choices.forEach(c=>{const btn=document.createElement('button');btn.className='choice-btn';const cost=chooseCost(c),blocked=cost>state.cash;btn.disabled=blocked;if(blocked)btn.style.opacity='.45';btn.innerHTML=`<strong>${c.label}</strong><span>${c.hint}${blocked?' · Cash insuffisant':''}</span>`;btn.addEventListener('click',()=>choose(c));$('choices').appendChild(btn)})}
function showEvent(){currentEvent=pickEvent();renderCurrentEvent()}
function pushHistory(){state.history.push({month:state.month,cash:Math.round(state.cash),valuation:Math.round(state.valuation),revenue:Math.round(state.revenue)})}
function render(){const b=expenseBreakdown();$('cash').textContent=fmtMoney(state.cash);$('revenue').textContent=fmtMoney(state.revenue);$('expenses').textContent=fmtMoney(state.expenses);$('expenses').title=`Salaires ${fmtMoney(b.salaries)} · Infra ${fmtMoney(b.infra)} · Marketing ${fmtMoney(b.marketing)} · Dette ${fmtMoney(b.debtCost)}`;$('valuation').textContent=fmtMoney(state.valuation);$('users').textContent=fmt(state.users);$('customers').textContent=fmt(state.customers);$('team').textContent=state.employees===0?'Solo':`${fmt(state.team)} (${fmt(state.employees)} salarié${state.employees>1?'s':''})`;$('equity').textContent=(state.equity*100).toFixed(1)+' %';$('price').textContent=fmtMoney(state.price)+'/mois';$('conversion').textContent=(state.customers/state.users*100).toFixed(1)+' %';$('reputation').textContent=Math.round(state.reputation)+'/100';$('product').textContent=Math.round(state.product)+'/100';$('growth').textContent=(state.growth*100).toFixed(1)+' %';$('month-label').textContent='Mois '+state.month;$('cash').className=state.cash<0?'negative':'';$('revenue').className=state.profit>=0?'positive':'';drawChart()}
function drawChart(){const canvas=$('history-chart'),dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect(),width=Math.max(300,rect.width||900),height=260;canvas.width=width*dpr;canvas.height=height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);const pad={l:52,r:16,t:18,b:30},w=width-pad.l-pad.r,h=height-pad.t-pad.b,hist=state.history;if(!hist.length)return;const values=hist.flatMap(p=>[Math.max(0,p.valuation),Math.max(0,p.cash)]),max=Math.max(1000,...values)*1.08;ctx.strokeStyle='rgba(143,155,170,.18)';ctx.lineWidth=1;ctx.fillStyle='#8f9baa';ctx.font='11px system-ui';for(let i=0;i<=4;i++){const y=pad.t+h*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke();ctx.fillText(compactMoney(max*(1-i/4)),4,y+4)}const plot=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.beginPath();hist.forEach((p,i)=>{const x=pad.l+(hist.length===1?w/2:i*w/Math.max(1,hist.length-1)),y=pad.t+h-(Math.max(0,p[key])/max)*h;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)});ctx.stroke()};plot('valuation','#77f29c');plot('cash','#79a8ff');ctx.fillStyle='#8f9baa';ctx.fillText('M1',pad.l,height-8);ctx.textAlign='right';ctx.fillText('M'+state.month,width-pad.r,height-8);ctx.textAlign='left'}
function compactMoney(n){if(n>=1e9)return(n/1e9).toFixed(1)+' Md€';if(n>=1e6)return(n/1e6).toFixed(1)+' M€';if(n>=1e3)return(n/1e3).toFixed(0)+' k€';return Math.round(n)+' €'}
function addFeed(label,text){const item=document.createElement('div');item.className='feed-item';item.innerHTML=`<b>${label}</b><span>${text}</span>`;$('feed').prepend(item)}
function endGame(won,reason){$('game-screen').classList.add('hidden');$('end-screen').classList.remove('hidden');const worth=(reason==='acquisition'?state.flags.exitPrice:state.valuation)*state.equity,endings={win:["UNICORNE","Ta startup vaut plus d’un milliard.","Tu as construit une entreprise à l’échelle d’une licorne."],acquisition:["EXIT","Ta startup a été rachetée.",`Prix de sortie : ${fmtMoney(state.flags.exitPrice)}. Tu possèdes encore ${(state.equity*100).toFixed(1)} %.`],profitable:["INDÉPENDANT RENTABLE","Tu termines avec une entreprise rentable.","Tu n’as pas atteint le milliard, mais tu as construit une société durable et profitable."],cash:["FAILLITE","La startup n’a plus de solution de financement.","Le cash est négatif et la dette ou la perte de confiance ne permet plus de refinancer la société."],reputation:["CRISE DE CONFIANCE","La réputation est tombée à zéro.","Les utilisateurs et le marché ne font plus confiance au produit."],founder:["ÉVINCÉ","Tu ne contrôles presque plus rien.","Après les dilutions successives, ta part est devenue trop faible pour rester réellement aux commandes."],time:["FIN DE RUN","La fenêtre de marché s’est refermée.","Après 8 ans, la société n’a ni atteint le milliard ni construit une activité suffisamment rentable."]},[kicker,title,copy]=endings[reason]||endings.time;$('end-kicker').textContent=kicker;$('end-title').textContent=title;$('end-copy').textContent=copy;$('end-valuation').textContent=fmtMoney(reason==='acquisition'?state.flags.exitPrice:state.valuation);$('end-equity').textContent=(state.equity*100).toFixed(1)+' %';$('end-worth').textContent=fmtMoney(worth);$('end-revenue').textContent=fmtMoney(state.revenue)}

$('start-btn').addEventListener('click',resetGame);
$('restart-btn').addEventListener('click',resetGame);
$('play-again-btn').addEventListener('click',resetGame);
window.addEventListener('resize',()=>{if(state.history?.length)drawChart()});