(function(){
const VERSION='V0.7.1';
const OPENERS={PRODUCT:['Les retours support convergent depuis plusieurs semaines','Les données d’usage montrent un point de friction net','Trois entretiens clients récents racontent la même histoire'],SALES:['Une opportunité commerciale concrète vient d’arriver','Ton pipeline commercial bouge et une décision doit être prise vite','Un prospect sérieux met une condition sur la table'],MARKETING:['Un canal d’acquisition commence à envoyer un signal intéressant','Ton équipe observe un changement dans les performances marketing','Une occasion de gagner rapidement de la visibilité se présente'],TEAM:['La charge de travail commence à modifier le rythme de l’entreprise','Une décision humaine importante arrive au mauvais moment','Ton organisation atteint une limite que tu gérais jusque-là seul'],FINANCE:['Ta trésorerie oblige à regarder les prochains mois de plus près','Une nouvelle option de financement apparaît','Le rapport entre croissance et runway devient un sujet immédiat'],COMPETITION:['Le marché vient de bouger et tes clients commencent à le remarquer','Un concurrent change les règles du jeu sur ton segment','La pression concurrentielle devient concrète dans les discussions clients'],INFRA:['Les métriques techniques montrent que la marge de sécurité diminue','Un incident récent révèle une faiblesse de ton infrastructure','La croissance commence à solliciter des composants jusque-là tranquilles'],REPUTATION:['La perception publique de Scale Up évolue rapidement','Un signal de réputation commence à atteindre tes prospects','Une conversation externe prend assez d’ampleur pour exiger une décision'],LEGAL:['Un point juridique jusque-là théorique devient concret','Une vente ou un partenariat révèle une faiblesse contractuelle','La croissance de la société fait apparaître une obligation que tu pouvais ignorer au début'],STRATEGY:['Les données des derniers mois font apparaître un choix stratégique','Un signal marché inattendu devient trop fort pour être ignoré','La startup arrive à un carrefour : continuer pareil ou concentrer ses ressources']};
const CONSEQUENCE={PRODUCT:['Si tu te trompes, tu peux immobiliser plusieurs semaines de roadmap sans améliorer la rétention.','Le choix peut modifier la conversion, le churn et la vitesse de développement.'],SALES:['Le contrat peut apporter du revenu, mais aussi du support, des concessions et une dépendance à un gros client.','La décision touche directement le revenu, la marge et la qualité de ton portefeuille clients.'],MARKETING:['Le vrai enjeu est de savoir si la croissance achetée coûtera moins que la valeur générée par les nouveaux clients.','Un mauvais canal peut brûler du cash rapidement ; un bon peut accélérer toute la run.'],TEAM:['Un recrutement augmente la capacité, mais transforme immédiatement une partie de ton runway en charge fixe.','La décision affectera à la fois la vitesse d’exécution, le burn mensuel et la dépendance au fondateur.'],FINANCE:['Le financement peut sauver le runway, mais son prix se paie en dilution, dette ou perte de vitesse.','Ce choix déterminera combien de mois il te reste pour atteindre une économie plus saine.'],COMPETITION:['Réagir trop fort peut te détourner de tes clients ; ne rien faire peut laisser le rival définir le marché.','Le choix peut toucher tes prix, ton positionnement et la confiance des prospects.'],INFRA:['Investir trop tôt immobilise du cash ; attendre trop longtemps peut provoquer une panne au pire moment.','La décision oppose runway immédiat et risque opérationnel futur.'],REPUTATION:['La façon dont tu réponds peut transformer un incident isolé en preuve de sérieux — ou en crise durable.','Le choix influencera la confiance, le bouche-à-oreille et parfois la conversion commerciale.'],LEGAL:['Économiser maintenant peut créer une dette juridique beaucoup plus chère lorsque les contrats grossissent.','Le choix peut débloquer une vente, protéger la société ou repousser un risque qui reviendra plus tard.'],STRATEGY:['Concentrer les ressources peut accélérer le product-market fit, mais réduit les options si le signal est trompeur.','La décision peut changer durablement le type de clients, la croissance et le produit que tu construis.']};
const pick=a=>a[Math.floor(Math.random()*a.length)];
function runway(){const burn=Math.max(0,state.expenses-state.revenue);if(burn<=0)return 'rentable';return state.cash<=0?'0 mois':`${Math.max(0,state.cash/burn).toFixed(1)} mois`;}
function richerDescription(e){const category=OPENERS[e.category]?e.category:'STRATEGY';const cash=fmtMoney(state.cash),ca=fmtMoney(state.revenue),cost=fmtMoney(state.expenses);const context=e.description?e.description.replace(/Cash .*$/,'').trim():'';return `${pick(OPENERS[category])} : ${e.title.toLowerCase()}. ${context} ${pick(CONSEQUENCE[category])} Situation actuelle : ${cash} de cash, ${ca}/mois de CA, ${cost}/mois de coûts et environ ${runway()} de runway.`.replace(/\s+/g,' ').trim();}
const previousRender=renderCurrentEvent;
renderCurrentEvent=function(){
  previousRender();
  const e=currentEvent;if(!e)return;
  $('event-description').textContent=richerDescription(e);
  $('event-risk').textContent=`Risque ${e.risk}`;
};
queueMicrotask(()=>{document.title='Scale Up — '+VERSION;const badge=document.querySelector('.hero h1')?.nextElementSibling;if(badge)badge.textContent=VERSION;const p=document.querySelector('#start-screen p:not(.kicker)');if(p)p.textContent='Les scénarios donnent maintenant le contexte, les enjeux économiques et les conséquences possibles avant chaque décision. Les compteurs de “vues” ont été retirés.';});
})();