(function(){
const VERSION='V0.7';
const CONTEXTS=[
  'alors que le cash devient serré','pendant une phase de croissance rapide','avec une équipe encore minuscule','alors que les clients deviennent plus exigeants','dans un marché qui ralentit','au moment où un concurrent accélère','avec une réputation encore fragile','alors que ton produit commence à mûrir','pendant que ton acquisition coûte plus cher','avec un mois de résultats meilleurs que prévu'
];
const TOPICS={
PRODUCT:['onboarding trop long','fonctionnalité demandée par trois gros clients','mobile encore médiocre','bugs après une mise à jour','fonction IA réclamée par le marché','intégration avec un outil populaire','offre gratuite trop généreuse','dette technique qui ralentit les livraisons','accessibilité insuffisante','roadmap devenue illisible','temps de chargement trop élevé','recherche interne peu pertinente','permissions utilisateurs trop limitées','exports de données trop pauvres','notifications jugées envahissantes'],
SALES:['pilote gratuit demandé par un grand compte','remise de 30 % exigée par un prospect','prospect étranger prêt à signer','agence qui veut revendre le produit','ancien client qui veut revenir','partenaire qui propose un canal de vente','client annuel qui renégocie','administration intéressée mais lente','groupe international qui veut centraliser ses achats','client stratégique tenté par un rival','prospect qui demande un essai de 60 jours','client qui veut payer seulement au résultat','demande de contrat pluriannuel','client qui veut une exclusivité','prospect qui exige une personnalisation lourde'],
MARKETING:['newsletter très ciblée','créateur de contenu enthousiaste','publicités devenues trop chères','article SEO qui décolle','salon professionnel imminent','programme de parrainage demandé','communauté qui se crée spontanément','plateforme de lancement disponible','podcast spécialisé intéressé','campagne LinkedIn prometteuse','webinaire qui attire des inscrits','partenariat de contenu possible','comparateur logiciel qui veut te référencer','campagne email qui s’essouffle','avis clients positifs peu exploités'],
TEAM:['développeur senior disponible','commercial expérimenté disponible','support client débordé','cofondateur potentiel','freelance expert disponible','alternant prometteur','responsable produit possible','growth marketer disponible','CTO externe proposé','designer senior intéressé','premier manager à recruter','salarié performant qui demande une augmentation','salarié en difficulté','conflit entre produit et vente','équipe qui réclame plus de télétravail'],
FINANCE:['business angel intéressé','banque prête à financer','fonds seed qui te contacte','investisseur prêt à faire un bridge','aide publique accessible','prêteur basé sur le revenu','accélérateur qui propose un ticket','family office intéressé','investisseur stratégique intéressé','micro-fonds prêt à signer','clients qui paient en retard','facture fournisseur importante qui arrive','crédits cloud disponibles','possibilité de prévente annuelle','proposition de SAFE convertible'],
COMPETITION:['concurrent qui copie ta fonction clé','plateforme qui baisse ses prix','startup financée qui attaque ta niche','acteur américain qui arrive','nouvel entrant freemium','ancien partenaire devenu rival','géant qui annonce un produit proche','solution open source gratuite','concurrent low-cost agressif','rival premium qui débauche un client','comparatif public défavorable','concurrent qui recrute ton ancien salarié','nouvelle norme qui favorise un rival','rival qui signe un partenariat majeur','concurrent qui offre une migration gratuite'],
INFRA:['base de données qui sature','cloud qui augmente ses tarifs','paiements qui génèrent des erreurs','API qui ralentit','sauvegardes jamais restaurées','authentification fragile','pipeline de données instable','emails transactionnels retardés','file de tâches saturée','analytics qui ne tiendra pas 10× le trafic','logs insuffisants pour diagnostiquer','coûts stockage qui explosent','temps de réponse international mauvais','dépendance critique à un seul fournisseur','monitoring trop rudimentaire'],
REPUTATION:['avis négatif qui circule','journaliste qui veut t’interviewer','expert qui critique le produit','client mécontent très visible','communauté en ligne sceptique','créateur qui recommande ton produit','gros client qui menace de témoigner','association qui pose des questions','ancien salarié qui critique','influenceur qui compare les solutions','retard public sur une fonctionnalité promise','hausse de prix mal reçue','support jugé trop lent','rumeur infondée sur les données','bug partagé massivement sur les réseaux'],
LEGAL:['RGPD qui bloque une vente','CGU obsolètes','licence open source ambiguë','propriété intellectuelle mal documentée','contrat salarié trop simple','TVA internationale complexe','SLA avec pénalités','clause contractuelle risquée','accessibilité insuffisante','traitement des données à clarifier','marque trop proche d’un concurrent','facturation dans un nouveau pays','demande de suppression de données complexe','contrat de sous-traitance incomplet','conditions de remboursement floues'],
STRATEGY:['niche qui convertit deux fois mieux','nouveau pays avec traction','offre annuelle plus rentable','API publique très demandée','segment enterprise qui accélère','segment indépendant inattendu','marketplace envisageable','freemium qui pourrait accélérer','offre premium demandée','acquéreur potentiel qui approche','produit adjacent possible','partenariat distribution exclusif','pivot vers une industrie précise','modèle usage-based à tester','internationalisation plus tôt que prévu']
};
const DOMAINS=Object.keys(TOPICS);
const usedKey='v07used';
const pick=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function detail(){return `Cash ${fmtMoney(state.cash)} · CA ${fmtMoney(state.revenue)}/mois · coûts ${fmtMoney(state.expenses)}/mois · produit ${Math.round(state.product)}/100 · réputation ${Math.round(state.reputation)}/100.`}
function domainWeight(d){let w=1;const burn=Math.max(1,state.expenses-state.revenue),run=state.profit>=0?99:Math.max(0,state.cash/burn);if(d==='SALES'&&state.revenue<1000)w+=5;if(d==='FINANCE'&&run<5)w+=4;if(d==='PRODUCT'&&state.product<58)w+=3;if(d==='REPUTATION'&&state.reputation<45)w+=3;if(d==='INFRA'&&state.users>900*Math.max(1,state.infraLevel))w+=3;if(d==='TEAM'&&(state.cash<2500||state.revenue<700))w*=.2;if(state.v07last===d)w*=.25;return Math.max(.05,w)}
function chooseDomain(){let rows=DOMAINS.map(d=>[d,domainWeight(d)]),r=Math.random()*rows.reduce((s,x)=>s+x[1],0);for(const [d,w] of rows){r-=w;if(r<=0)return d}return rows[0][0]}
function outcomeText(d,style,subject){const pools={
PRODUCT:{build:[`Le ${subject} progresse et le churn devrait baisser.`,`Tu transformes un irritant produit en avantage mesurable.`,`La qualité perçue monte, ce qui aide conversion et rétention.`],test:[`Tu obtiens des données avant de refaire tout le produit.`,`Le test réduit l’incertitude à faible coût.`,`Tu vérifies si le problème mérite vraiment une grosse roadmap.`],delay:[`Tu conserves le cash mais le ${subject} reste non résolu.`,`Le sujet est repoussé et peut réapparaître plus cher plus tard.`,`Tu gardes le focus ailleurs, au prix d’une dette produit supplémentaire.`]},
SALES:{close:[`Le deal transforme une intention en cash réel.`,`Tu sécurises du revenu et une preuve de marché.`,`La vente apporte du cash mais ajoute des attentes client.`],negotiate:[`Tu conserves le prospect sans accepter toutes ses conditions.`,`Le compromis protège mieux la marge que l’acceptation brute.`,`Tu réduis le risque commercial sans abandonner la discipline de prix.`],walk:[`Tu protèges le produit et la marge mais renonces au revenu immédiat.`,`Tu évites un client potentiellement coûteux à servir.`,`Tu gardes le focus, mais perds une occasion d’apprentissage marché.`]},
MARKETING:{scale:[`L’acquisition accélère, mais le CAC doit maintenant être surveillé.`,`Tu profites de la fenêtre d’attention et gagnes rapidement des utilisateurs.`,`Le volume augmente, avec un risque de trafic moins qualifié.`],test:[`Tu mesures le canal avant d’y mettre un gros budget.`,`Le test donne un signal de CAC sans mettre le runway en danger.`,`Tu achètes de l’apprentissage marketing plutôt que du volume.`],organic:[`Tu préserves le cash et la croissance reste organique.`,`Le canal n’est pas exploité, mais ton runway reste intact.`,`Tu refuses de payer pour une croissance dont la qualité n’est pas prouvée.`]},
TEAM:{hire:[`La capacité augmente mais le burn mensuel monte durablement.`,`Tu réduis le goulot du fondateur au prix d’un nouveau coût fixe.`,`L’équipe gagne une compétence qui manquait, mais ton runway raccourcit.`],temp:[`Tu débloques le problème sans créer tout de suite un gros coût fixe.`,`La solution temporaire protège la flexibilité financière.`,`Tu achètes du temps, sans construire autant de savoir interne.`],wait:[`Tu gardes un burn faible, mais le goulot humain reste présent.`,`Le cash est protégé mais la charge du fondateur augmente.`,`Tu repousses le recrutement et acceptes une croissance plus lente.`]},
FINANCE:{equity:[`Tu achètes du runway contre une dilution permanente.`,`Le risque de faillite baisse, mais ta part personnelle diminue.`,`Tu finances l’accélération avec du capital externe et partages davantage la valeur future.`],debt:[`Tu récupères du cash sans dilution, mais ajoutes une obligation de remboursement.`,`Tu conserves tes parts au prix d’un burn financier plus élevé.`,`La dette protège le capital mais augmente le risque si la croissance ralentit.`],cut:[`Tu prolonges le runway sans lever, mais sacrifies une partie de la vitesse.`,`La discipline de coûts améliore la survie au prix d’une croissance plus faible.`,`Tu évites dilution et dette, mais réduis tes options offensives.`]},
COMPETITION:{fight:[`Tu défends ton différentiel, mais dépenses pour répondre au rival.`,`La pression concurrentielle baisse si ton amélioration est réellement visible.`,`Tu renforces ta position, avec le risque de piloter en réaction aux autres.`],position:[`Tu changes le terrain de comparaison au lieu d’entrer dans une guerre frontale.`,`Le repositionnement peut protéger ta marge si les clients comprennent la différence.`,`Tu adaptes l’offre sans copier le concurrent.`],ignore:[`Tu gardes le cap, mais assumes le risque de perdre du terrain.`,`Tu refuses la réaction à chaud et protèges le focus.`,`L’inaction économise du cash, mais peut coûter des clients si la menace est réelle.`]},
INFRA:{invest:[`La fiabilité augmente et le risque de panne future diminue.`,`Tu paies maintenant pour éviter une panne plus coûteuse plus tard.`,`La capacité technique augmente avant que la croissance ne la rende urgente.`],opt:[`Tu réduis le coût ou la charge sans lancer une grosse migration.`,`L’optimisation améliore l’efficacité mais ne supprime pas forcément la limite structurelle.`,`Tu gagnes du temps technique avec un investissement modéré.`],risk:[`Tu conserves le cash mais la probabilité d’incident reste ouverte.`,`Tu reportes l’investissement et gardes plus de runway.`,`Le risque opérationnel reste dans le système et peut revenir brutalement.`]},
REPUTATION:{public:[`Tu montres publiquement que le problème est pris au sérieux.`,`La transparence peut restaurer la confiance si les actes suivent.`,`Tu reprends le contrôle du récit mais rends aussi ta promesse publique.`],private:[`Tu règles le cas sans donner plus d’ampleur au problème.`,`La réponse ciblée limite le bruit tout en réparant la relation.`,`Tu corriges le fond, mais une partie du marché ne verra pas l’effort.`],silent:[`Tu évites d’amplifier le sujet, avec un risque si la critique continue.`,`Le silence économise de l’attention mais peut être interprété comme de l’indifférence.`,`Tu paries sur l’oubli plutôt que sur une réponse active.`]},
LEGAL:{full:[`Le risque juridique baisse fortement et les ventes enterprise deviennent plus simples.`,`Tu paies maintenant pour éviter un blocage contractuel plus tard.`,`La conformité devient un actif commercial en plus d’une protection.`],minimum:[`Tu débloques l’urgence avec moins de dépenses.`,`Le minimum règle le point bloquant mais laisse une zone grise.`,`Tu dépenses peu aujourd’hui, avec un risque résiduel.`],delay:[`Tu gardes le cash mais conserves un risque légal non traité.`,`Le report protège le runway à court terme mais peut bloquer une future vente.`,`Tu acceptes une dette juridique qui peut coûter davantage lorsque la société grossira.`]},
STRATEGY:{focus:[`Tu concentres les ressources sur une hypothèse claire.`,`Le focus peut accélérer le product-market fit mais ferme certaines options.`,`Tu transformes un signal marché en pari stratégique explicite.`],experiment:[`Tu apprends avant de rendre la décision irréversible.`,`Le test protège contre un pivot prématuré.`,`Tu gardes plusieurs options ouvertes, au prix d’une exécution moins rapide.`],stay:[`Tu protèges la cohérence de la stratégie actuelle.`,`La stabilité évite la dispersion mais peut faire manquer une vraie fenêtre marché.`,`Tu privilégies l’exécution au changement de cap.`]}};return pick(pools[d][style])}
function explain(d,style,subject,good){const m={
PRODUCT:{build:['Bon : tu attaques directement un facteur de churn ou de conversion.','Mauvais : le coût d’opportunité peut être élevé si peu de clients vivent réellement ce problème.'],test:['Bon : tu réduis l’incertitude avant d’engager la roadmap.','Mauvais : un petit test peut sous-estimer un problème structurel.'],delay:['Bon : tu protèges ton runway et ton focus.','Mauvais : la dette produit peut dégrader rétention et bouche-à-oreille.']},
SALES:{close:['Bon : du cash immédiat améliore runway et preuve de marché.','Mauvais : un deal trop spécifique peut augmenter le coût de service et la concentration client.'],negotiate:['Bon : tu cherches à sauver le deal sans détruire ta marge.','Mauvais : trop négocier peut rallonger le cycle de vente et perdre le momentum.'],walk:['Bon : tu évites un mauvais revenu qui consomme plus qu’il ne rapporte.','Mauvais : tu perds du cash et une source d’apprentissage client.']},
MARKETING:{scale:['Bon : si le canal convertit, tu accélères pendant une fenêtre favorable.','Mauvais : si le CAC dépasse la valeur client, chaque nouvel utilisateur détruit du cash.'],test:['Bon : tu mesures CAC et conversion avant de scaler.','Mauvais : le petit échantillon peut donner un faux signal.'],organic:['Bon : aucun CAC payé, donc meilleur runway.','Mauvais : tu peux laisser un canal rentable à tes concurrents.']},
TEAM:{hire:['Bon : tu retires un goulot humain durable.','Mauvais : le salaire devient une charge fixe même si la croissance ralentit.'],temp:['Bon : tu gardes de la flexibilité tout en débloquant le travail.','Mauvais : le savoir reste moins dans l’entreprise et le coût horaire peut être élevé.'],wait:['Bon : ton burn reste faible.','Mauvais : le fondateur devient le facteur limitant de la croissance.']},
FINANCE:{equity:['Bon : plus de runway réduit le risque de mourir avant le product-market fit.','Mauvais : la dilution réduit ta part de chaque euro de valeur future.'],debt:['Bon : tu finances sans céder de capital.','Mauvais : les intérêts et remboursements restent dus même dans un mauvais mois.'],cut:['Bon : tu prolonges la durée de vie de la société avec tes propres ressources.','Mauvais : couper trop fort peut casser la croissance qui devait justement te sauver.']},
COMPETITION:{fight:['Bon : tu défends ton avantage avec un signal visible pour les clients.','Mauvais : tu peux gaspiller du cash à courir derrière chaque mouvement concurrent.'],position:['Bon : tu évites une guerre de prix en changeant les critères de comparaison.','Mauvais : le nouveau positionnement peut brouiller ton message.'],ignore:['Bon : tu restes concentré sur ta propre thèse produit.','Mauvais : si la menace est réelle, le retard sera plus coûteux à rattraper.']},
INFRA:{invest:['Bon : la prévention réduit la probabilité d’un incident qui ferait perdre confiance et clients.','Mauvais : tu immobilises du cash avant d’avoir besoin de toute la capacité.'],opt:['Bon : tu repousses le gros investissement en améliorant l’efficacité.','Mauvais : l’optimisation ne remplace pas toujours une architecture adaptée.'],risk:['Bon : tu gardes ton runway pour la croissance.','Mauvais : une panne peut coûter bien plus que l’économie réalisée.']},
REPUTATION:{public:['Bon : une réponse visible peut stopper une crise avant qu’elle ne devienne la version dominante.','Mauvais : tu amplifies parfois un sujet que peu de gens avaient vu.'],private:['Bon : tu répares la relation sans donner plus d’audience au problème.','Mauvais : l’amélioration reste invisible pour ceux qui ont vu la critique publique.'],silent:['Bon : certains sujets meurent d’eux-mêmes sans intervention.','Mauvais : le silence peut être interprété comme une absence de contrôle ou d’empathie.']},
LEGAL:{full:['Bon : conformité et contrats solides débloquent souvent les grands comptes.','Mauvais : c’est du cash dépensé sans revenu immédiat.'],minimum:['Bon : tu débloques l’urgence avec un coût limité.','Mauvais : les zones non traitées peuvent revenir lors du prochain audit.'],delay:['Bon : tu concentres les ressources sur le produit et les ventes.','Mauvais : un problème juridique peut devenir brutalement bloquant quand la société grossit.']},
STRATEGY:{focus:['Bon : le focus améliore vitesse d’exécution et clarté du positionnement.','Mauvais : si l’hypothèse est fausse, tu concentres aussi le risque.'],experiment:['Bon : tu achètes de l’information avant de pivoter.','Mauvais : tester trop longtemps peut faire rater la fenêtre.'],stay:['Bon : tu protèges l’équipe de la dispersion.','Mauvais : la stabilité devient de l’inertie si le marché a réellement changé.']}};return m[d][style][good?0:1]+` Ici, le sujet était : ${subject}.`}
function actionSet(d,subject){const cost=Math.round(140+state.month*24+Math.random()*240);const map={
PRODUCT:[['build',`Résoudre complètement : ${subject}`,'Investissement produit durable',cost,s=>{s.cash-=cost;s.product+=6;s.conversion+=.004}],['test',`Prototyper avant de généraliser`,'Test limité et mesurable',Math.round(cost*.35),s=>{s.cash-=Math.round(cost*.35);s.product+=2.5;s.conversion+=.001}],['delay',`Reporter et mesurer davantage`,'Cash préservé',0,s=>{s.product-=.6}]],
SALES:[['close',`Signer avec des garde-fous`,'Cash immédiat, engagement client',0,s=>{const a=500+state.month*85;s.cash+=a;s.reputation+=2}],['negotiate',`Négocier une version plus saine`,'Compromis prix/périmètre',0,s=>{s.conversion+=.003;s.reputation+=1}],['walk',`Refuser le deal`,'Focus préservé',0,s=>{s.product+=1.5}]],
MARKETING:[['scale',`Accélérer sur cette opportunité`,'Plus de portée, plus de risque CAC',cost,s=>{s.cash-=cost;s.users*=1.12+Math.random()*.12;s.marketing+=Math.round(cost*.08)}],['test',`Lancer un test plafonné`,'Petit budget, mesure du canal',Math.round(cost*.3),s=>{s.cash-=Math.round(cost*.3);s.users*=1.04+Math.random()*.05}],['organic',`Rester organique`,'0 € de CAC payé',0,s=>{s.growth-=.001}]],
TEAM:[['hire',`Recruter pour traiter : ${subject}`,'Capacité durable, coût fixe',cost,s=>{s.cash-=cost;s.employees++;s.team++;s.product+=3}],['temp',`Prendre une aide temporaire`,'Flexible, moins durable',Math.round(cost*.4),s=>{s.cash-=Math.round(cost*.4);s.product+=1.5}],['wait',`Absorber en interne pour l’instant`,'Aucun coût fixe nouveau',0,s=>{s.growth-=.002}]],
FINANCE:[['equity',`Lever du capital maintenant`,'Runway contre dilution',0,s=>{const a=Math.round(clamp(s.valuation*(.15+.08*Math.random()),2500,150000)),di=.05+.08*Math.random();s.cash+=a;s.equity*=1-di;s.totalRaised+=a}],['debt',`Utiliser de la dette`,'Cash sans dilution, intérêts',0,s=>{const a=Math.round(clamp(s.valuation*(.06+.05*Math.random()),1500,60000));s.cash+=a;s.debt+=a}],['cut',`Réduire le burn et rester autonome`,'Pas de dilution ni dette',0,s=>{s.marketing=Math.round(s.marketing*.55);s.growth-=.003}]],
COMPETITION:[['fight',`Répliquer avec un avantage produit`,'Défense active',cost,s=>{s.cash-=cost;s.product+=4;s.reputation+=2}],['position',`Changer le terrain de comparaison`,'Positionnement plutôt que guerre frontale',0,s=>{s.conversion+=.004;s.price=Math.max(6,s.price*.98)}],['ignore',`Ne pas réagir immédiatement`,'Focus conservé',0,s=>{if(Math.random()<.45){s.users*=.96;s.reputation-=1.5}}]],
INFRA:[['invest',`Corriger l’infrastructure maintenant`,'Fiabilité et capacité',cost,s=>{s.cash-=cost;s.infraLevel++;s.reputation+=1.5}],['opt',`Optimiser l’existant`,'Moins cher, limite repoussée',Math.round(cost*.35),s=>{s.cash-=Math.round(cost*.35);s.infraEfficiency=clamp(s.infraEfficiency*.94,.55,1)}],['risk',`Attendre et surveiller`,'Cash préservé, risque incident',0,s=>{if(Math.random()<.28){s.users*=.92;s.reputation-=5}}]],
REPUTATION:[['public',`Répondre publiquement avec des preuves`,'Réponse visible',Math.round(cost*.2),s=>{s.cash-=Math.round(cost*.2);s.reputation+=5}],['private',`Traiter directement les personnes concernées`,'Réparation ciblée',0,s=>{s.reputation+=2.5}],['silent',`Ne pas amplifier le sujet`,'Aucune dépense',0,s=>{if(Math.random()<.4)s.reputation-=4}]],
LEGAL:[['full',`Mettre le dossier complètement en conformité`,'Risque fortement réduit',cost,s=>{s.cash-=cost;s.compliance=(s.compliance||50)+9}],['minimum',`Traiter uniquement le point bloquant`,'Correction partielle',Math.round(cost*.35),s=>{s.cash-=Math.round(cost*.35);s.compliance=(s.compliance||50)+3}],['delay',`Reporter le traitement`,'Cash préservé, dette juridique',0,s=>{if(Math.random()<.25){s.cash-=cost*1.5;s.reputation-=3}}]],
STRATEGY:[['focus',`Faire de ce signal une priorité stratégique`,'Focus fort',0,s=>{s.growth+=.007;s.users*=1.05}],['experiment',`Tester pendant 2 mois avant de pivoter`,'Apprentissage avant engagement',0,s=>{s.product+=1.5;s.conversion+=.002}],['stay',`Conserver la stratégie actuelle`,'Stabilité',0,s=>{s.product+=.5;s.growth-=.001}]]};return map[d].map(([style,label,hint,cost,apply])=>({label,hint,cost,good:explain(d,style,subject,true),bad:explain(d,style,subject,false),apply:s=>{apply(s);return outcomeText(d,style,subject)}}))}
function nextEvent(){if(!state.v07){state.v07={used:[]};}let d=chooseDomain(),topic,ctx,key,tries=0;do{topic=Math.floor(Math.random()*TOPICS[d].length);ctx=Math.floor(Math.random()*CONTEXTS.length);key=`${d}-${topic}-${ctx}`;tries++}while(state.v07.used.includes(key)&&tries<100);state.v07.used.push(key);if(state.v07.used.length>400)state.v07.used.shift();state.v07last=d;const subject=TOPICS[d][topic];return{id:`v07-${key}`,category:d,risk:pick(['Faible','Modéré','Modéré','Élevé']),title:subject.charAt(0).toUpperCase()+subject.slice(1),description:`${CONTEXTS[ctx]}. ${detail()}`,choices:actionSet(d,subject)}}
queueMicrotask(()=>{
  pickEvent=nextEvent;
  document.title='Scale Up — '+VERSION;
  const badge=document.querySelector('.hero h1')?.nextElementSibling;if(badge)badge.textContent=VERSION;
  const h=document.querySelector('#start-screen h2');if(h)h.textContent='1 500+ situations. Des décisions vraiment différentes.';
  const p=document.querySelector('#start-screen p:not(.kicker)');if(p)p.textContent='Les événements, réponses et débriefs sont désormais générés selon le problème précis et les mécanismes économiques touchés : runway, CAC, churn, dilution, dette technique, concentration client, réputation et plus.';
  console.info('Scale Up V0.7 — richer scenario, answer and debrief diversity');
});
})();