(function(){
'use strict';
const X=window.ScaleUpV09={VERSION:'V0.9',STORE:'scale-up-v09-runs',MAX_RUNS:30};
X.STARTS={
grocer:{name:'Épicier du coin',icon:'🛒',desc:'Petit commerce local : stock, fournisseurs, passage et marge.',salary:900,labels:['Passage','Qualité offre','Panier moyen'],s:{cash:1000,users:220,customers:32,price:22,employees:0,team:1,reputation:58,product:48,growth:.055,conversion:.145,equity:1,debt:0},bonus:{SUPPLY:4,OPERATIONS:3,CUSTOMER:3},ladder:[[0,'Épicier du coin'],[25000,'Gérant de supérette'],[150000,'Gérant de marché'],[1000000,'Directeur de supermarché'],[10000000,'Propriétaire d’hypermarché'],[100000000,'Groupe de centres commerciaux'],[1000000000,'Empire commercial mondial']]},
freelance:{name:'Indépendant',icon:'🧠',desc:'Tu vends ton expertise : clients, capacité, tarifs et recrutement.',salary:1800,labels:['Prospects','Expertise','Panier client'],s:{cash:2500,users:55,customers:5,price:520,employees:0,team:1,reputation:62,product:56,growth:.06,conversion:.09,equity:1,debt:0},bonus:{SALES:4,TEAM:2,CUSTOMER:3},ladder:[[0,'Indépendant'],[100000,'Studio spécialisé'],[500000,'Agence locale'],[1500000,'Agence nationale'],[15000000,'Groupe de conseil'],[150000000,'Réseau international'],[1000000000,'Holding mondiale']]},
ecommerce:{name:'Boutique e-commerce',icon:'📦',desc:'Acquisition, stock, logistique, retours et marque.',salary:1200,labels:['Visiteurs','Qualité boutique','Panier moyen'],s:{cash:5000,users:900,customers:48,price:54,employees:0,team:1,reputation:52,product:50,growth:.09,conversion:.055,equity:1,debt:0},bonus:{MARKETING:3,SUPPLY:4,CUSTOMER:2,OPERATIONS:2},ladder:[[0,'Petite boutique en ligne'],[120000,'Marque émergente'],[700000,'Boutique nationale'],[3000000,'Marketplace spécialisée'],[30000000,'Groupe retail'],[300000000,'Leader omnicanal'],[1000000000,'Empire e-commerce mondial']]},
saas:{name:'SaaS de garage',icon:'💻',desc:'Produit logiciel récurrent : churn, cloud, intégrations et levées.',salary:1500,labels:['Utilisateurs','Produit','Abonnement'],s:{cash:8000,users:420,customers:24,price:29,employees:0,team:1,reputation:50,product:52,growth:.12,conversion:.058,equity:1,debt:0},bonus:{PRODUCT:4,INFRA:4,FINANCE:2},ladder:[[0,'Projet de garage'],[50000,'Micro-SaaS'],[500000,'Startup'],[5000000,'Scale-up'],[100000000,'Leader international'],[1000000000,'Licorne'],[10000000000,'Décacorne']]},
pme:{name:'PME familiale',icon:'🏭',desc:'Entreprise installée : équipe, production, fournisseurs et expansion.',salary:1700,labels:['Prospects','Qualité offre','Panier client'],s:{cash:25000,users:650,customers:70,price:185,employees:3,team:4,reputation:66,product:61,growth:.055,conversion:.108,equity:1,debt:5000},bonus:{OPERATIONS:4,SUPPLY:3,TEAM:2,EXPANSION:3},ladder:[[0,'PME locale'],[600000,'PME régionale'],[3000000,'ETI émergente'],[20000000,'Groupe national'],[200000000,'Champion européen'],[1000000000,'Multinationale'],[10000000000,'Conglomérat mondial']]},
funded:{name:'Startup financée',icon:'🚀',desc:'Capital et équipe dès le départ, avec une forte pression de croissance.',salary:2100,labels:['Utilisateurs','Produit','Abonnement'],s:{cash:100000,users:3500,customers:170,price:39,employees:6,team:7,reputation:55,product:62,growth:.18,conversion:.052,equity:.78,debt:0},bonus:{FINANCE:3,TEAM:2,MARKETING:2,INFRA:2,EXPANSION:3},ladder:[[0,'Seed startup'],[1000000,'Startup financée'],[10000000,'Scale-up'],[100000000,'Leader de catégorie'],[1000000000,'Licorne'],[10000000000,'Décacorne'],[100000000000,'Géant technologique']]}
};
X.DIFF={
discovery:{name:'Découverte',desc:'Plus de cash, coûts réduits, incidents moins sévères et davantage de temps.',cash:1.5,cost:.78,salary:.85,fail:.72,time:24,score:.75},
normal:{name:'Normal',desc:'Équilibré : les erreurs coûtent cher mais restent rattrapables.',cash:1,cost:1,salary:1,fail:1,time:0,score:1},
hard:{name:'Difficile',desc:'Moins de marge, coûts plus élevés et conséquences plus sévères.',cash:.88,cost:1.16,salary:1.12,fail:1.18,time:-12,score:1.25},
brutal:{name:'Brutal',desc:'Runway court, coûts élevés et très peu de droit à l’erreur.',cash:.72,cost:1.32,salary:1.22,fail:1.38,time:-24,score:1.6}
};
X.GOALS={
million:{name:'Premier million',desc:'Atteindre 1 M€ de valorisation.',kind:'valuation',target:1e6,months:72},
hundred:{name:'Champion à 100 M€',desc:'Atteindre 100 M€ de valorisation.',kind:'valuation',target:1e8,months:96},
billion:{name:'Le milliard',desc:'Atteindre 1 Md€ de valorisation.',kind:'valuation',target:1e9,months:120},
tenb:{name:'Empire à 10 Md€',desc:'Atteindre 10 Md€ de valorisation.',kind:'valuation',target:1e10,months:144},
cashmachine:{name:'Machine à cash',desc:'Atteindre 100 k€ de bénéfice mensuel avec au moins 50 % du capital.',kind:'profit',target:100000,months:120}
};
X.SUBJECTS={
PRODUCT:['offre devenue trop complexe','fonction clé très demandée','parcours client trop long','bugs après une mise à jour','innovation devenue attendue','offre gratuite trop généreuse','dette produit qui ralentit tout','expérience mobile insuffisante','fonction premium demandée','roadmap devenue illisible'],
SALES:['gros prospect qui exige une remise','essai gratuit très long','contrat annuel payé d’avance','prospect étranger prêt à signer','client qui demande une exclusivité','personnalisation lourde pour un grand compte','partenaire qui veut revendre ton offre','client stratégique tenté par un rival','appel d’offres inattendu','client qui veut payer au résultat'],
MARKETING:['publicités devenues trop chères','campagne qui devient virale','créateur qui parle de toi','article SEO qui décolle','newsletter très ciblée','salon professionnel imminent','programme de parrainage demandé','canal social qui convertit mieux que prévu','comparateur qui veut te référencer','campagne email qui s’essouffle'],
TEAM:['profil senior disponible','commercial expérimenté intéressé','support client débordé','cofondateur potentiel','freelance expert disponible','manager externe proposé','salarié performant qui demande une hausse','départ inattendu dans l’équipe','conflit produit-vente','poste critique sans remplaçant'],
FINANCE:['investisseur qui veut entrer','banque qui propose un financement','fonds qui te contacte','bridge possible en urgence','aide publique accessible','clients qui paient en retard','grosse échéance qui arrive','levée plus grosse mais plus dilutive','prévente annuelle possible','dette basée sur le revenu'],
COMPETITION:['concurrent qui copie ton offre','rival qui baisse ses prix','startup financée qui attaque ta niche','acteur étranger qui arrive','nouvel entrant gratuit','grand groupe qui lance une offre proche','comparatif public défavorable','rival qui débauche un client','partenariat majeur signé par un concurrent','migration gratuite proposée par un rival'],
INFRA:['capacité qui approche de la limite','fournisseur technique qui augmente ses tarifs','paiements qui échouent','système lent aux heures de pointe','sauvegardes jamais testées','dépendance critique à un fournisseur','risque de sécurité découvert','migration technique devenue inévitable','monitoring trop rudimentaire','stockage qui devient coûteux'],
REPUTATION:['avis négatif très visible','journaliste qui veut t’interviewer','expert qui critique ton offre','client mécontent très visible','communauté sceptique','ancien salarié qui critique','hausse de prix mal reçue','incident partagé massivement','retard public sur une promesse','rumeur sur les données'],
LEGAL:['conformité qui bloque une vente','conditions générales obsolètes','licence ou contrat ambigu','propriété intellectuelle mal documentée','fiscalité internationale complexe','SLA avec pénalités','marque trop proche d’un concurrent','nouveau règlement sectoriel','contrat salarié incomplet','conditions de remboursement floues'],
STRATEGY:['niche qui convertit deux fois mieux','nouveau pays avec traction','offre annuelle plus rentable','segment premium qui accélère','marketplace ou plateforme possible','offre freemium à tester','acquéreur potentiel qui approche','pivot vers une industrie précise','API publique très demandée','modèle à l’usage à tester'],
OPERATIONS:['délais qui s’allongent','erreurs manuelles répétées','procédure interne trop lente','coût de service qui augmente','outil interne qui ne suit plus','responsabilités mal réparties','activité très saisonnière','organisation dépendante d’une seule personne','qualité inégale entre équipes','coordination qui absorbe trop de temps'],
CUSTOMER:['clients qui demandent plus de support','hausse des annulations','demandes de remboursement','satisfaction qui baisse','groupe de clients très fidèle','segment qui coûte trop cher à servir','baisse de fréquence d’achat','besoin de fidélisation','gros client qui menace de partir','nouveau segment très engagé'],
SUPPLY:['fournisseur principal qui augmente ses prix','rupture de stock ou de capacité','nouveau fournisseur moins cher','partenaire logistique en retard','qualité variable des approvisionnements','stock dormant trop important','coût de livraison en hausse','dépendance à un seul fournisseur','matière première devenue rare','condition de paiement qui se durcit'],
EXPANSION:['deuxième implantation possible','nouveau quartier ou marché à tester','franchise proposée','local plus grand disponible','acquisition d’un petit concurrent','ouverture à l’étranger','nouvelle catégorie à lancer','grand distributeur intéressé','nouvelle région sous-servie','rachat d’un fournisseur possible']
};
X.FLAVOR={
grocer:{SUPPLY:['grossiste de produits frais qui change ses conditions','rupture sur un produit d’appel','produits frais perdus avant vente'],OPERATIONS:['files d’attente aux heures de pointe','rayons mal remplis en fin de journée'],EXPANSION:['local voisin qui se libère','marché couvert qui propose un emplacement']},
freelance:{SALES:['client qui élargit sans cesse le périmètre','grand compte qui veut réserver plusieurs jours par mois'],OPERATIONS:['trop de missions reposent uniquement sur toi','administratif qui absorbe une semaine entière']},
ecommerce:{SUPPLY:['best-seller presque en rupture','transporteur qui dégrade ses délais','taux de retours qui monte'],MARKETING:['campagne TikTok qui explose','marketplace qui augmente ses commissions']},
saas:{PRODUCT:['intégration API demandée par plusieurs clients','onboarding qui fait fuir les nouveaux','fonction IA demandée par le marché'],INFRA:['base de données qui sature','coûts cloud qui montent plus vite que le revenu'],CUSTOMER:['churn des petits comptes qui augmente','clients enterprise qui réclament un SLA']},
pme:{OPERATIONS:['outil critique qui tombe régulièrement en panne','planification de production devenue complexe'],SUPPLY:['matière première qui augmente brutalement','fournisseur historique devenu peu fiable']},
funded:{FINANCE:['board qui réclame une croissance plus rapide','fonds qui propose une série A agressive'],STRATEGY:['board qui pousse vers l’international','acquisition capable d’accélérer la roadmap']}
};
X.SCALE_EXTRA={
2:{TEAM:['première couche de management à construire'],OPERATIONS:['plusieurs équipes qui travaillent différemment'],EXPANSION:['implantation régionale à arbitrer']},
3:{FINANCE:['financement de croissance à structurer'],LEGAL:['contrats grands comptes de plus en plus exigeants'],TEAM:['directeur opérationnel à recruter'],EXPANSION:['rachat d’un concurrent régional']},
4:{STRATEGY:['portefeuille de marques à rationaliser'],TEAM:['comité de direction devenu nécessaire'],EXPANSION:['acquisition nationale possible'],REPUTATION:['prise de parole nationale sensible']},
5:{FINANCE:['dette structurée ou nouvelle levée majeure'],LEGAL:['autorité de régulation qui s’intéresse à toi'],EXPANSION:['entrée sur plusieurs pays en même temps'],STRATEGY:['fusion avec un grand acteur possible']},
6:{STRATEGY:['conglomérat à réorganiser'],LEGAL:['gouvernements qui négocient avec ton groupe'],FINANCE:['allocation de plusieurs milliards à arbitrer'],EXPANSION:['acquisition transformante internationale']}
};
X.CONTEXTS=['alors que la trésorerie se tend','pendant une phase de croissance rapide','avec une équipe sous pression','au moment où les clients deviennent plus exigeants','dans un marché qui ralentit','alors qu’un concurrent accélère','après plusieurs mois plutôt stables','au moment où ton statut vient de changer','avec une marge qui devient stratégique','alors que tu prépares la prochaine étape de croissance'];
X.STAKES=['La décision peut modifier durablement ta marge et ton runway.','Le mauvais choix peut sembler peu coûteux aujourd’hui mais devenir très cher avec le volume.','L’enjeu est de préserver le cash sans rater une vraie fenêtre de croissance.','Cette décision touche à la fois la vitesse d’exécution et la solidité de l’entreprise.','Tu dois arbitrer entre résultat immédiat et avantage durable.','Ce choix peut créer une conséquence qui ne sera visible que dans plusieurs mois.'];
X.OPEN={PRODUCT:'Les retours clients convergent',SALES:'Une négociation importante arrive à un point de bascule',MARKETING:'Un canal d’acquisition envoie un signal inhabituel',TEAM:'Ton organisation atteint une limite',FINANCE:'Le rapport entre croissance et runway devient urgent',COMPETITION:'Le marché vient de bouger',INFRA:'Ta marge de sécurité opérationnelle diminue',REPUTATION:'La perception publique évolue rapidement',LEGAL:'Un risque jusque-là théorique devient concret',STRATEGY:'Les derniers mois font apparaître un choix stratégique',OPERATIONS:'Le quotidien commence à coûter plus cher que prévu',CUSTOMER:'Le comportement de tes clients change',SUPPLY:'Ta chaîne d’approvisionnement devient stratégique',EXPANSION:'Une nouvelle étape de croissance devient possible'};
X.PERKS=[{id:'negotiator',name:'Négociateur',desc:'Meilleurs deals commerciaux et dilution réduite.'},{id:'operator',name:'Gestionnaire',desc:'Coûts d’exploitation réduits et incidents moins sévères.'},{id:'visionary',name:'Visionnaire',desc:'Les investissements produit rapportent davantage.'},{id:'recruiter',name:'Recruteur',desc:'Recrutements moins chers et plus efficaces.'},{id:'marketer',name:'Roi du marketing',desc:'Acquisition plus efficace lors des gros paris.'},{id:'financier',name:'Financier',desc:'Dette et levées plus favorables.'},{id:'brand',name:'Bâtisseur de marque',desc:'Réputation plus résistante et fidélité plus forte.'},{id:'strategist',name:'Stratège',desc:'Expansion et stratégie ont plus d’impact.'}];
X.PEOPLE_NAMES=['Sarah','Nassim','Lina','Hugo','Maya','Arthur','Inès','Yanis','Clara','Noah','Amel','Tom','Jade','Rayan','Zoé','Mehdi','Emma','Lucas'];
X.ROLES=[['employee','talent clé'],['investor','investisseur'],['client','client important'],['supplier','fournisseur stratégique'],['rival','dirigeant concurrent']];
})();