(function(){
'use strict';
const VERSION='V0.9';
const $v=id=>document.getElementById(id);
const rnd=a=>a[Math.floor(Math.random()*a.length)];
const cap=(n,a,b)=>Math.max(a,Math.min(b,n));
const NAMES=['Lina','Sarah','Mehdi','Thomas','Emma','Yanis','Nora','Alex','Camille','Hugo','Maya','Lucas'];
const START_LABELS={grocer:'Épicier du coin',freelance:'Indépendant',ecommerce:'Boutique e-commerce',saas:'SaaS de garage',pme:'PME familiale',funded:'Startup financée'};
const PERKS={
  manager:{name:'Gestionnaire',desc:'Tu récupères 10 % des dépenses liées aux décisions payantes.',icon:'📊'},
  negotiator:{name:'Négociateur',desc:'Les futures dilutions sont environ 15 % moins douloureuses.',icon:'🤝'},
  visionary:{name:'Visionnaire',desc:'Les décisions produit réussies donnent un bonus de qualité.',icon:'💡'},
  marketer:{name:'Growth instinct',desc:'Les décisions marketing réussies apportent davantage d’audience.',icon:'📣'},
  leader:{name:'Leader',desc:'Les décisions d’équipe renforcent davantage la réputation.',icon:'🧭'},
  operator:{name:'Opérateur',desc:'Les décisions opérations / infra donnent un bonus d’efficacité.',icon:'⚙️'}
};
function V(){
  if(!state.v09){
    const names=[...NAMES].sort(()=>Math.random()-.5);
    state.v09={decisions:[],pending:[],chain:null,rareCooldown:0,perkThresholds:[25000,250000,2500000,25000000,250000000],perks:[],nextPerk:0,characters:{employee:{name:names[0],role:'personne clé',relation:60},client:{name:names[1],role:'client important',relation:58},investor:{name:names[2],role:'investisseur',relation:50},rival:{name:names[3],role:'rival',relation:42}},badges:[],worldLog:[],startValuation:state.valuation||1000,startCash:state.cash||0};
  }
  return state.v09;
}
function snapshotV(){return{month:state.month,cash:state.cash,revenue:state.revenue,expenses:state.expenses,profit:state.profit,valuation:state.valuation,equity:state.equity,customers:state.customers,users:state.users,product:state.product,reputation:state.reputation,debt:state.debt};}
function money(n){return fmtMoney(Number.isFinite(n)?n:0)}
function runwayV(s=state){const burn=Math.max(0,(s.expenses||0)-(s.revenue||0));return burn<=0?99:Math.max(0,(s.cash||0)/burn)}
function setupWorldUI(){
  const game=$v('game-screen'); if(!game||$v('v09-world'))return;
  const sec=document.createElement('section');sec.id='v09-world';sec.className='v09-world';
  sec.innerHTML='<div class="v09-world-card"><span>MONDE VIVANT</span><strong id="v09-people">4 relations actives</strong><small id="v09-people-copy"></small></div><div class="v09-world-card"><span>EFFETS À VENIR</span><strong id="v09-pending">0 conséquence</strong><small id="v09-pending-copy">Tes décisions peuvent revenir plusieurs mois plus tard.</small></div><div class="v09-world-card"><span>COMPÉTENCES</span><strong id="v09-perks">Aucun perk</strong><small id="v09-perks-copy">Débloque des compétences en changeant d’échelle.</small></div>';
  const progress=game.querySelector('.progress-card'); progress?.after(sec);
  refreshWorldUI();
}
function refreshWorldUI(){
  if(!$v('v09-world')||!state.v09)return;const v=V(),c=Object.values(v.characters);
  $v('v09-people').textContent=`${c.length} relations actives`;
  $v('v09-people-copy').textContent=c.map(x=>`${x.name} ${Math.round(x.relation)}/100`).join(' · ');
  $v('v09-pending').textContent=`${v.pending.length} conséquence${v.pending.length>1?'s':''}`;
  $v('v09-pending-copy').textContent=v.pending.length?`Prochaine possible dès le mois ${Math.min(...v.pending.map(x=>x.due))}.`:'Aucune conséquence différée en attente.';
  $v('v09-perks').textContent=v.perks.length?v.perks.map(k=>PERKS[k]?.name||k).join(' · '):'Aucun perk';
}
function relation(key,delta){const p=V().characters[key];if(p)p.relation=cap(p.relation+delta,0,100)}
function scoreChoice(category,index,before){
  const rw=runwayV(before),cash=before.cash||0,profit=before.profit||0,eq=before.equity||1,prod=before.product||50,rep=before.reputation||50;
  let scores=[60,67,52],reasons=['Option offensive : potentiel élevé mais consommation de ressources.','Option mesurée : bon équilibre entre apprentissage, coût et risque.','Option prudente : protège le cash mais peut laisser le problème grandir.'];
  if(rw<3){scores=[42,74,78];reasons=['Runway critique : une grosse dépense est dangereuse.','Le compromis protège mieux la survie.','Préserver le cash est prioritaire avec moins de 3 mois de runway.'];}
  if(category==='FINANCE'){
    if(cash<0||rw<2.5){scores=[82,70,35];reasons=['Lever du capital réduit fortement le risque de faillite immédiate.','La dette évite la dilution mais augmente le burn futur.','Réduire seulement le burn peut être trop lent en urgence.'];}
    else if(eq<.35){scores=[45,72,78];reasons=['Nouvelle dilution alors que ta part est déjà faible.','La dette peut être préférable si les remboursements restent soutenables.','Préserver le capital devient important à ce niveau de dilution.'];}
  } else if(category==='PRODUCT'&&prod<50){scores=[82,70,38];reasons=['La qualité faible pénalise déjà conversion et rétention.','Tester limite le risque tout en améliorant le produit.','Reporter un problème produit déjà critique aggrave la dette produit.'];}
  else if(category==='REPUTATION'&&rep<40){scores=[84,70,30];reasons=['La confiance est déjà fragile : une réponse forte protège la survie commerciale.','Une réparation ciblée peut fonctionner mais reste moins visible.','Le silence est risqué quand la réputation est basse.'];}
  else if(category==='TEAM'&&rw<4){scores=[40,76,70];reasons=['Un coût fixe supplémentaire raccourcit trop le runway.','Une solution temporaire enlève le goulot sans figer les coûts.','Attendre protège le cash, mais conserve le goulot humain.'];}
  else if(category==='MARKETING'&&profit<0&&rw<5){scores=[48,77,68];reasons=['Scaler avant d’avoir une économie saine peut accélérer les pertes.','Tester le canal mesure le CAC avant d’engager davantage de cash.','Rester organique protège le runway mais apprend moins vite.'];}
  else if(['INFRA','LEGAL','OPERATIONS','SUPPLY'].includes(category)&&state.valuation>1000000){scores=[80,70,44];reasons=['À cette échelle, le coût d’un incident devient supérieur au coût de prévention.','L’option intermédiaire réduit une partie du risque.','Reporter une dette opérationnelle à grande échelle peut coûter très cher.'];}
  return{scores,reasons,best:scores.indexOf(Math.max(...scores)),chosen:scores[index]||0};
}
function scheduleConsequence(category,index,eventTitle){
  const v=V();let due=state.month+2+Math.floor(Math.random()*5),type='echo',severity=index===2?2:index===0?1:0;
  const map={PRODUCT:'produit',SALES:'client',MARKETING:'canal',TEAM:'équipe',FINANCE:'financement',COMPETITION:'concurrent',INFRA:'infrastructure',REPUTATION:'réputation',LEGAL:'juridique',STRATEGY:'stratégie',OPERATIONS:'opérations',CUSTOMER:'clients',SUPPLY:'fournisseur',EXPANSION:'expansion'};
  v.pending.push({due,category,index,type,severity,source:eventTitle,label:map[category]||'décision'});
}
function consequenceEvent(x){
  const bad=x.index===2||x.severity>1,person=V().characters[x.category==='TEAM'?'employee':x.category==='FINANCE'?'investor':x.category==='COMPETITION'?'rival':'client'];
  return{id:`v09-consequence-${state.month}-${Math.random()}`,category:x.category,risk:bad?'Élevé':'Modéré',v09Type:'consequence',title:bad?`Une ancienne décision sur ${x.label} revient`:`Ton choix sur ${x.label} produit un nouvel effet`,description:`Au mois ${state.month}, la décision « ${x.source} » refait surface. ${person.name}, ${person.role}, est directement concerné. ${bad?'Le risque que tu avais accepté devient concret.':'Le choix passé ouvre maintenant une nouvelle possibilité.'}`,choices:[
    {label:'Traiter le sujet à fond',hint:'Coût immédiat · risque réduit',cost:Math.round(Math.max(100,Math.sqrt(Math.max(1000,state.valuation))*2)),good:'Tu fermes la boucle et limites une nouvelle récidive.',bad:'Tu consommes du cash pour réparer un choix ancien.',apply:s=>{s.reputation+=2;s.product+=1.5;relation('client',2);return'Tu règles le sujet proprement et rassures les parties concernées.'}},
    {label:'Trouver un compromis',hint:'Impact intermédiaire',cost:Math.round(Math.max(50,Math.sqrt(Math.max(1000,state.valuation))*.7)),good:'Tu réduis le risque sans mobiliser trop de ressources.',bad:'Une partie du problème reste ouverte.',apply:s=>{s.reputation+=.8;return'Le compromis évite que la situation dégénère.'}},
    {label:'Assumer le risque',hint:'0 € · conséquence possible',cost:0,good:'Tu gardes ton cash.',bad:'Le problème peut continuer à peser sur la croissance.',apply:s=>{if(bad){s.reputation-=3;s.product-=1;s.users*=.97}return'Tu choisis de ne pas réinvestir sur ce dossier.'}}
  ]};
}
function chainEvent(stage){
  const rival=V().characters.rival,client=V().characters.client;
  if(stage===1)return{id:`v09-chain-1-${state.month}`,category:'COMPETITION',risk:'Élevé',v09Type:'chain',v09Stage:1,title:`${rival.name} attaque ton marché`,description:`${rival.name}, ton rival récurrent, baisse fortement ses prix et contacte directement ${client.name}, un de tes clients importants. Ce choix lancera une histoire en plusieurs étapes.`,choices:[
    {label:'Défendre le client et la valeur',hint:'Investissement commercial',cost:Math.round(Math.max(150,state.revenue*.18)),good:'Tu protèges la relation sans casser tout ton pricing.',bad:'La défense consomme du temps et du cash.',apply:s=>{s.reputation+=2;relation('client',8);relation('rival',-5);return'Tu renforces la relation client et refuses la guerre de prix pure.'}},
    {label:'Baisser les prix',hint:'Conversion + · marge -',cost:0,good:'Tu rends la comparaison immédiate plus favorable.',bad:'Le pricing peut rester durablement sous pression.',apply:s=>{s.price*=.94;s.conversion+=.004;relation('rival',-3);return'Tu réponds sur le prix et rends le marché plus agressif.'}},
    {label:'Ignorer et te différencier',hint:'Produit + · risque client',cost:0,good:'Tu protèges ton positionnement.',bad:'Le client peut partir avant que la différence soit visible.',apply:s=>{s.product+=2;relation('client',-4);return'Tu refuses de suivre la guerre commerciale et renforces ton offre.'}}
  ]};
  return{id:`v09-chain-2-${state.month}`,category:'STRATEGY',risk:'Modéré',v09Type:'chain',v09Stage:2,title:`La guerre avec ${rival.name} change de terrain`,description:`Quelques mois après votre affrontement, ${rival.name} cherche maintenant un partenariat majeur. ${client.name} attend de voir qui deviendra la référence du marché.`,choices:[
    {label:'Former une alliance avant lui',hint:'Croissance + · cash -',cost:Math.round(Math.max(300,state.revenue*.22)),good:'Tu transformes la rivalité en course à la distribution.',bad:'Le partenariat peut distraire l’équipe.',apply:s=>{s.users*=1.09;s.growth+=.004;relation('client',5);return'Tu prends l’initiative et sécurises un nouveau canal.'}},
    {label:'Consolider ta niche',hint:'Qualité + · réputation +',cost:0,good:'Tu renforces ton avantage là où tu es déjà crédible.',bad:'Tu laisses potentiellement le rival prendre le grand public.',apply:s=>{s.product+=3;s.reputation+=2;return'Tu deviens plus difficile à remplacer sur ton segment principal.'}},
    {label:'Proposer un rapprochement au rival',hint:'Rare · peut ouvrir un exit',cost:0,good:'Une coopération peut arrêter la destruction de valeur.',bad:'Tu donnes des informations à un concurrent.',apply:s=>{relation('rival',12);if(Math.random()<.25){s.flags.acquired=true;s.flags.exitPrice=Math.round(s.valuation*1.35)}return'Les discussions avec le rival deviennent beaucoup plus sérieuses.'}}
  ]};
}
function rareEvent(){
  const v=V(),types=['viral','crisis','star','offer','fraud'],t=rnd(types),employee=v.characters.employee,investor=v.characters.investor;
  if(t==='viral')return{id:`v09-rare-viral-${state.month}`,category:'MARKETING',risk:'Rare',v09Type:'rare',title:'Ton entreprise devient virale pendant 48 heures',description:'Une publication inattendue déclenche une vague massive d’attention. Le trafic peut multiplier la croissance, mais ton organisation n’est pas forcément prête.',choices:[{label:'Profiter de la vague immédiatement',hint:'Audience ++ · risque infra',cost:Math.round(Math.max(200,state.revenue*.15)),good:'Tu exploites une fenêtre très rare.',bad:'La qualité peut souffrir si la capacité ne suit pas.',apply:s=>{s.users*=1.35;s.reputation+=2;if(s.infraLevel<2)s.product-=2;return'La vague apporte un afflux exceptionnel de nouveaux utilisateurs.'}},{label:'Canaliser la croissance',hint:'Croissance + · qualité protégée',cost:Math.round(Math.max(100,state.revenue*.06)),good:'Tu transformes le buzz en croissance plus soutenable.',bad:'Tu laisses une partie du pic inexploité.',apply:s=>{s.users*=1.18;s.product+=1;return'Tu absorbes la vague sans trop dégrader l’expérience.'}},{label:'Ne rien forcer',hint:'0 €',cost:0,good:'Aucun risque financier supplémentaire.',bad:'Une occasion rare peut disparaître.',apply:s=>{s.users*=1.08;return'Le buzz retombe, mais laisse une base un peu plus large.'}}]};
  if(t==='crisis')return{id:`v09-rare-crisis-${state.month}`,category:'FINANCE',risk:'Rare',v09Type:'rare',title:'Le marché se retourne brutalement',description:'Une crise externe réduit la demande et rend le financement plus difficile. Les prochains mois seront plus tendus.',choices:[{label:'Passer immédiatement en mode survie',hint:'Burn - · croissance -',cost:0,good:'Tu prolonges le runway avant que la crise ne s’aggrave.',bad:'Tu ralentis au moment où certains concurrents disparaissent.',apply:s=>{s.marketing*=.55;s.growth*=.85;s.reputation+=1;return'Tu protèges la trésorerie et acceptes une croissance plus lente.'}},{label:'Continuer à investir',hint:'Risque élevé · parts de marché',cost:Math.round(Math.max(200,state.revenue*.2)),good:'Les crises peuvent permettre de prendre des parts de marché.',bad:'Si la demande reste faible, le cash part très vite.',apply:s=>{s.users*=1.08;s.growth+=.003;return'Tu joues l’offensive alors que les autres ralentissent.'}},{label:'Chercher du capital maintenant',hint:'Cash + · dilution',cost:0,good:'Tu sécurises du runway avant un possible durcissement supplémentaire.',bad:'La valorisation de négociation est moins favorable.',apply:s=>{const a=Math.max(3000,s.valuation*.12),pre=Math.max(1000,s.valuation*.9),d=a/(pre+a);s.cash+=a;s.equity*=1-d;return`Tu sécurises ${money(a)}, au prix d’une dilution de ${(d*100).toFixed(1)} %.`}}]};
  if(t==='star')return{id:`v09-rare-star-${state.month}`,category:'TEAM',risk:'Rare',v09Type:'rare',title:`${employee.name} te présente un profil exceptionnel`,description:`Une personne très reconnue dans ton secteur est prête à rejoindre l’aventure. Le coût est élevé, mais ce recrutement peut changer le niveau d’exécution.`,choices:[{label:'Faire le recrutement exceptionnel',hint:'Équipe + · coût fixe +',cost:Math.round(Math.max(300,state.salaryPerEmployee*.6)),good:'Le talent peut accélérer plusieurs dimensions à la fois.',bad:'Le coût fixe restera même si la croissance ralentit.',apply:s=>{s.employees++;s.team++;s.product+=4;s.reputation+=3;relation('employee',7);return'Le recrutement change immédiatement le niveau d’expertise de l’équipe.'}},{label:'Mission de 3 mois',hint:'Flexibilité',cost:Math.round(Math.max(180,state.salaryPerEmployee*.25)),good:'Tu profites du talent sans créer immédiatement un coût permanent.',bad:'La connaissance peut repartir avec la personne.',apply:s=>{s.product+=2;s.reputation+=1;return'La mission débloque plusieurs sujets sans engagement permanent.'}},{label:'Refuser',hint:'Cash préservé',cost:0,good:'Tu protèges le runway.',bad:'Une opportunité de talent rare disparaît.',apply:s=>{relation('employee',-2);return'Tu gardes une structure légère.'}}]};
  if(t==='offer')return{id:`v09-rare-offer-${state.month}`,category:'STRATEGY',risk:'Rare',v09Type:'rare',title:`${investor.name} apporte une offre de rachat`,description:`Un acquéreur propose environ ${money(state.valuation*1.45)} pour acheter l’entreprise. Tu peux sortir maintenant ou continuer ton objectif initial.`,choices:[{label:'Accepter le rachat',hint:'Fin immédiate possible',cost:0,good:'Tu transformes une valeur théorique en sortie concrète.',bad:'Tu abandonnes tout potentiel futur.',apply:s=>{s.flags.acquired=true;s.flags.exitPrice=Math.round(s.valuation*1.45);return'L’offre est acceptée.'}},{label:'Négocier puis refuser',hint:'Réputation + · indépendance',cost:0,good:'Tu crées un signal de valeur sans quitter la course.',bad:'L’offre peut ne jamais revenir.',apply:s=>{s.reputation+=3;relation('investor',5);return'Tu conserves ton indépendance et utilises l’offre comme signal de marché.'}},{label:'Refuser immédiatement',hint:'Focus conservé',cost:0,good:'Aucune distraction stratégique.',bad:'Tu ignores une option de liquidité réelle.',apply:s=>{s.product+=1;return'Tu restes entièrement concentré sur la croissance.'}}]};
  return{id:`v09-rare-fraud-${state.month}`,category:'OPERATIONS',risk:'Rare',v09Type:'rare',title:'Une anomalie financière interne apparaît',description:'Un contrôle révèle des paiements incohérents. Rien ne prouve encore une fraude, mais ignorer le signal serait dangereux.',choices:[{label:'Auditer complètement',hint:'Coût · sécurité ++',cost:Math.round(Math.max(180,state.revenue*.08)),good:'Tu limites un risque de perte beaucoup plus importante.',bad:'L’audit coûte du temps et de l’argent.',apply:s=>{s.reputation+=1;s.compliance+=5;return'L’audit clarifie la situation et renforce les contrôles.'}},{label:'Contrôle ciblé',hint:'Coût faible',cost:Math.round(Math.max(80,state.revenue*.03)),good:'Tu vérifies rapidement les zones les plus risquées.',bad:'Un problème plus large peut passer inaperçu.',apply:s=>{s.compliance+=2;return'Le contrôle réduit une partie de l’incertitude.'}},{label:'Attendre une deuxième alerte',hint:'0 € · risque',cost:0,good:'Aucun coût immédiat.',bad:'Une fraude réelle peut continuer.',apply:s=>{if(Math.random()<.4)s.cash-=Math.max(300,s.revenue*.12);return'Tu gardes le sujet sous surveillance.'}}]};
}
function scaleEvent(){
  if(state.valuation<1000000)return null;const v=V(),employee=v.characters.employee;
  const high=state.valuation>=100000000;
  return{id:`v09-scale-${state.month}-${Math.random()}`,category:high?'STRATEGY':'TEAM',risk:'Échelle',v09Type:'scale',title:high?'Ton entreprise devient trop grande pour être dirigée comme avant':'Tu ne peux plus tout valider toi-même',description:high?`À ${money(state.valuation)} de valorisation, les décisions concernent désormais plusieurs marchés, équipes et partenaires. La gouvernance devient un avantage compétitif.`:`${employee.name} te fait remarquer que toutes les décisions remontent encore jusqu’à toi. Ce fonctionnement ralentit l’entreprise à mesure qu’elle grandit.`,choices:[{label:high?'Créer une vraie direction exécutive':'Déléguer un périmètre complet',hint:'Structure + · coût +',cost:Math.round(Math.max(500,state.revenue*.06)),good:'Tu augmentes la capacité de décision de l’organisation.',bad:'Tu ajoutes une couche de management coûteuse.',apply:s=>{s.product+=2;s.growth+=.003;s.reputation+=1;relation('employee',5);return'L’organisation gagne en autonomie.'}},{label:'Standardiser les décisions',hint:'Process + · coût modéré',cost:Math.round(Math.max(180,state.revenue*.02)),good:'Tu réduis les décisions répétitives sans trop alourdir la structure.',bad:'Les processus peuvent devenir bureaucratiques.',apply:s=>{s.infraEfficiency*=.96;s.product+=1;return'Les équipes avancent avec moins de validations.'}},{label:'Rester très centralisé',hint:'0 € · vitesse -',cost:0,good:'Tu gardes un contrôle maximal.',bad:'Le fondateur devient le principal goulot.',apply:s=>{s.growth-=.002;return'Le contrôle reste fort, mais la vitesse d’exécution souffre.'}}]};
}
function maybePerk(){
  if(!state.v09)return;const v=V(),t=v.perkThresholds[v.nextPerk];if(!t||state.valuation<t||$v('v09-perk-modal'))return;v.nextPerk++;
  const available=Object.keys(PERKS).filter(k=>!v.perks.includes(k)).sort(()=>Math.random()-.5).slice(0,4);if(!available.length)return;
  const modal=document.createElement('div');modal.id='v09-perk-modal';modal.className='v09-modal';modal.innerHTML=`<section class="v09-modal-card"><div><p class="kicker">NOUVEAU PALIER</p><h2>Choisis une compétence de dirigeant</h2><p>Ta société vient de franchir ${money(t)} de valorisation. Cette compétence restera active pour toute la run.</p></div><div class="perk-grid">${available.map(k=>`<button class="perk-btn" data-perk="${k}"><strong>${PERKS[k].icon} ${PERKS[k].name}</strong><span>${PERKS[k].desc}</span></button>`).join('')}</div></section>`;document.body.appendChild(modal);
  modal.querySelectorAll('.perk-btn').forEach(b=>b.onclick=()=>{v.perks.push(b.dataset.perk);v.badges.push(`Perk : ${PERKS[b.dataset.perk].name}`);modal.remove();addFeed('Compétence',`Tu débloques « ${PERKS[b.dataset.perk].name} ».`);refreshWorldUI();});
}
function applyPerks(before,category,index,cost){const v=V();if(v.perks.includes('manager')&&cost>0)state.cash+=cost*.10;if(v.perks.includes('negotiator')&&category==='FINANCE'&&state.equity<before.equity){const lost=before.equity-state.equity;state.equity+=lost*.15}if(v.perks.includes('visionary')&&category==='PRODUCT'&&index<2)state.product+=1.5;if(v.perks.includes('marketer')&&category==='MARKETING'&&index<2)state.users*=1.06;if(v.perks.includes('leader')&&category==='TEAM'&&index<2)state.reputation+=1.5;if(v.perks.includes('operator')&&['OPERATIONS','INFRA','SUPPLY'].includes(category)&&index<2)state.infraEfficiency=cap(state.infraEfficiency*.97,.45,1);state.equity=cap(state.equity,0,1);}
const oldPickEvent=pickEvent;
pickEvent=function(){
  const v=V();
  const due=v.pending.findIndex(x=>x.due<=state.month);if(due>=0){const x=v.pending.splice(due,1)[0];return consequenceEvent(x)}
  if(v.chain?.due<=state.month){const stage=v.chain.stage;v.chain=stage>=2?null:{stage:2,due:state.month+3};return chainEvent(stage)}
  if(v.rareCooldown>0)v.rareCooldown--;
  if(state.month>3&&v.rareCooldown<=0&&Math.random()<.035){v.rareCooldown=6;return rareEvent()}
  if(state.month>5&&!v.chain&&Math.random()<.025){v.chain={stage:2,due:state.month+3};return chainEvent(1)}
  if(Math.random()<.16){const e=scaleEvent();if(e)return e}
  return oldPickEvent();
};
const oldChoose=choose;
choose=function(choice){
  V();const before=snapshotV(),event=currentEvent,category=event?.category||'DÉCISION',index=Math.max(0,event?.choices?.indexOf(choice)??0),cost=chooseCost(choice)||0,analysis=scoreChoice(category,index,before),labels=(event?.choices||[]).map(c=>c.label),bestLabel=labels[analysis.best]||choice.label;
  const monthBefore=state.month;oldChoose(choice);
  const advanced=state.month>monthBefore;
  if(!advanced&&choice.quit)return;
  if(advanced){
    applyPerks(before,category,index,cost);
    state.product=cap(state.product,5,100);state.reputation=cap(state.reputation,0,100);state.equity=cap(state.equity,0,1);
    recalcSnapshotOnly();
    const after=snapshotV();
    V().decisions.push({month:before.month,event:event?.title||'Décision',category,choice:choice.label,choiceIndex:index,bestIndex:analysis.best,bestChoice:bestLabel,score:analysis.chosen,bestScore:analysis.scores[analysis.best],reason:analysis.reasons[analysis.best],before,after,alternatives:labels});
    if(event?.v09Type==='chain'&&event.v09Stage===1&&!V().chain)V().chain={stage:2,due:state.month+3};
    if(!['consequence','rare'].includes(event?.v09Type)&&Math.random()<(index===2?.7:index===0?.38:.25))scheduleConsequence(category,index,event?.title||'ancienne décision');
    if(category==='TEAM')relation('employee',index===0?4:index===1?2:-2);if(category==='FINANCE')relation('investor',index===0?5:index===1?1:-2);if(category==='CUSTOMER'||category==='SALES')relation('client',index===0?4:index===1?2:-2);if(category==='COMPETITION')relation('rival',index===2?2:-3);
    if(typeof render==='function')render();refreshWorldUI();maybePerk();
  }
};
function scoreRun(){const v=V(),difficulty={discovery:.8,normal:1,hard:1.2,brutal:1.45}[state.v08?.difficulty||'normal']||1,wealth=state.valuation*state.equity,profit=Math.max(0,state.profit),months=Math.max(1,state.month),retention=.6+.4*state.equity;return Math.max(0,Math.round((Math.log10(Math.max(1000,wealth))*900+Math.log10(Math.max(1,profit+1))*350+state.reputation*12+state.product*10)*difficulty*retention*(1+Math.min(.35,24/months))));}
function achievements(){const v=V(),a=[];if(state.equity>=.75&&state.valuation>=1000000)a.push('Dynastie — plus de 75 % conservés');if(state.profit>=100000)a.push('Machine à cash — 100 k€+ de bénéfice mensuel');if(state.debt<=0&&state.equity>=.95&&state.valuation>=1000000)a.push('Bootstrap — croissance presque sans capital externe');if(state.reputation>=85)a.push('Marque de confiance — réputation 85+');if(v.perks.length>=3)a.push('Dirigeant complet — 3 compétences débloquées');if(v.characters.client.relation>=80)a.push('Clients ambassadeurs');return a;}
function ensureEndExtras(){
  const end=$v('end-screen');if(!end||$v('v09-end-chart'))return;
  const card=document.createElement('section');card.id='v09-end-chart';card.className='end-chart-card';card.innerHTML='<div class="chart-head"><div><span class="mini-label">RÉCAP DE LA RUN</span><strong>Évolution de ton entreprise</strong></div><div class="legend"><span>Valorisation · Cash · CA</span></div></div><canvas id="v09-recap-canvas" width="900" height="260"></canvas><div class="end-extra-actions"><button id="v09-analysis-btn" class="ghost-btn">Meilleure trajectoire possible</button><button id="v09-png-btn" class="ghost-btn">Télécharger PNG</button><button id="v09-jpg-btn" class="ghost-btn">Télécharger JPEG</button><button id="v09-share-btn" class="primary-btn">Partager ma run</button></div><p class="share-note">L’analyse optimale est une estimation basée sur le contexte de chaque décision et les mécanismes du jeu.</p>';
  const actions=end.querySelector('.end-actions');actions?.before(card);
  $v('v09-analysis-btn').onclick=openAnalysis;$v('v09-png-btn').onclick=()=>exportCard('png');$v('v09-jpg-btn').onclick=()=>exportCard('jpeg');$v('v09-share-btn').onclick=shareRun;
}
function drawRecap(){const c=$v('v09-recap-canvas');if(!c||!state.history?.length)return;const ctx=c.getContext('2d'),W=c.width,H=c.height,pad=38,h=state.history,max=Math.max(1,...h.flatMap(x=>[x.valuation||0,x.cash||0,x.revenue||0]));ctx.clearRect(0,0,W,H);ctx.fillStyle='#10151b';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#28333e';for(let i=0;i<5;i++){let y=20+i*(H-50)/4;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(W-12,y);ctx.stroke()}const plot=(key,color)=>{ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();h.forEach((p,i)=>{const x=pad+(W-pad-16)*(i/Math.max(1,h.length-1)),y=H-25-(Math.max(0,p[key]||0)/max)*(H-50);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()};plot('valuation','#77f29c');plot('cash','#79a8ff');plot('revenue','#f0c56b');ctx.fillStyle='#93a0ad';ctx.font='12px system-ui';ctx.fillText('M1',pad,H-7);ctx.textAlign='right';ctx.fillText('M'+state.month,W-14,H-7);ctx.textAlign='left';}
function analysisEstimate(){const d=V().decisions;if(!d.length)return{mult:1,valuation:state.valuation,cash:state.cash,worth:state.valuation*state.equity};const missed=d.reduce((s,x)=>s+Math.max(0,x.bestScore-x.score),0),avg=missed/d.length,mult=cap(1+avg/115,1,2.6);return{mult,valuation:Math.round(state.valuation*mult),cash:Math.round(state.cash+Math.max(0,state.revenue)*avg/8),worth:Math.round(state.valuation*mult*Math.min(1,state.equity+(1-state.equity)*.08))};}
function openAnalysis(){let modal=$v('v09-analysis-modal');if(modal)modal.remove();const d=V().decisions,e=analysisEstimate();modal=document.createElement('div');modal.id='v09-analysis-modal';modal.className='v09-modal';modal.innerHTML=`<section class="v09-modal-card"><div><p class="kicker">ANALYSE DE RUN</p><h2>Meilleure trajectoire estimée</h2><p>L’algorithme rejuge chaque décision avec les chiffres que tu avais exactement à ce moment-là.</p></div><div class="analysis-summary"><strong>Meilleur résultat estimé : ${money(e.valuation)} de valorisation</strong><span>Cash estimé ${money(e.cash)} · valeur de ta part ${money(e.worth)} · potentiel ≈ ×${e.mult.toFixed(2)} par rapport à ta trajectoire finale.</span></div><div class="analysis-list">${d.map(x=>`<article class="analysis-item"><div class="head"><strong>Mois ${x.month} · ${x.event}</strong><span>${x.score===x.bestScore?'✓ choix optimal':'écart '+(x.bestScore-x.score)+' pts'}</span></div><div class="yours">Ton choix : ${x.choice}</div><div class="best">Meilleur choix estimé : ${x.bestChoice}</div><p>${x.reason}</p></article>`).join('')||'<p>Aucune décision analysable.</p>'}</div><button id="v09-analysis-close" class="primary-btn">Fermer</button></section>`;document.body.appendChild(modal);$v('v09-analysis-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};}
function shareCanvas(){const c=document.createElement('canvas');c.width=1200;c.height=630;const x=c.getContext('2d'),v=V(),hist=state.history||[],score=scoreRun(),start=START_LABELS[state.v08?.start]||'Entreprise';x.fillStyle='#0c1116';x.fillRect(0,0,c.width,c.height);x.fillStyle='#77f29c';x.font='bold 64px system-ui';x.fillText('SCALE UP',64,86);x.fillStyle='#94a2b0';x.font='22px system-ui';x.fillText(`V0.9 · ${start} · ${state.v08?.difficulty||'normal'} · mois ${state.month}`,66,122);x.fillStyle='#eef4f9';x.font='bold 38px system-ui';x.fillText(`Valorisation ${money(state.valuation)}`,66,190);x.font='26px system-ui';x.fillText(`Ta part ${(state.equity*100).toFixed(1)} %  ·  Valeur ${money(state.valuation*state.equity)}`,66,235);x.fillText(`CA ${money(state.revenue)}/mois  ·  Résultat ${money(state.profit)}/mois`,66,275);x.fillStyle='#77f29c';x.font='bold 34px system-ui';x.fillText(`SCORE ${score.toLocaleString('fr-FR')}`,66,330);const left=66,top=370,W=1068,H=190,max=Math.max(1,...hist.flatMap(p=>[p.valuation||0,p.cash||0]));x.strokeStyle='#24303a';x.strokeRect(left,top,W,H);const plot=(key,color)=>{x.strokeStyle=color;x.lineWidth=4;x.beginPath();hist.forEach((p,i)=>{const px=left+W*i/Math.max(1,hist.length-1),py=top+H-(Math.max(0,p[key]||0)/max)*H;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()};plot('valuation','#77f29c');plot('cash','#79a8ff');x.fillStyle='#9aa8b5';x.font='18px system-ui';x.fillText('Valorisation',left,594);x.fillText('Cash',left+145,594);x.textAlign='right';x.fillText('scale-up · partage de run',1135,594);x.textAlign='left';return c;}
function exportCard(type){const c=shareCanvas(),mime=type==='jpeg'?'image/jpeg':'image/png',a=document.createElement('a');a.href=c.toDataURL(mime,type==='jpeg'?.92:1);a.download=`scale-up-run-${Date.now()}.${type==='jpeg'?'jpg':'png'}`;a.click();}
async function shareRun(){const c=shareCanvas();if(!navigator.share){exportCard('png');return}c.toBlob(async blob=>{try{const file=new File([blob],'scale-up-run.png',{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({title:'Ma run Scale Up',text:`Score ${scoreRun().toLocaleString('fr-FR')} · ${money(state.valuation)} de valorisation`,files:[file]});else await navigator.share({title:'Ma run Scale Up',text:`Scale Up — Score ${scoreRun().toLocaleString('fr-FR')} · ${money(state.valuation)} de valorisation`});}catch(e){if(e?.name!=='AbortError')exportCard('png')}},'image/png');}
const oldRender=render;render=function(){oldRender();setupWorldUI();refreshWorldUI();maybePerk();};
const oldEndGame=endGame;endGame=function(won,reason){oldEndGame(won,reason);ensureEndExtras();drawRecap();const score=scoreRun(),a=achievements();let extra=$v('v09-end-summary');if(!extra){extra=document.createElement('div');extra.id='v09-end-summary';extra.className='analysis-summary';$v('end-copy')?.after(extra)}extra.innerHTML=`<strong class="v09-score">Score ${score.toLocaleString('fr-FR')}</strong><span>${a.length?a.join(' · '):'Aucun trophée secondaire cette fois.'}</span>`;};
queueMicrotask(()=>{document.title='Scale Up — '+VERSION;const badge=document.querySelector('.hero h1')?.nextElementSibling;if(badge)badge.textContent=VERSION;setupWorldUI();console.info('Scale Up V0.9 — monde vivant, conséquences, chaînes, personnages, perks, analyse et partage');});
})();